### PR TITLE
Un-scale output distances

### PR DESCRIPTION
**Pull request by achirkin**
Reverts the scaling of input data and queries that normally happens for int8/uint8 types before distance computation.
Reuses the ivf-pq post-processing step for that.

Along the way, replaces the custom `fragment_scale` helper with the `utils::mapping` that is shared among several ANN methods.

Solves https://github.com/rapidsai/raft/issues/1457

### CODE REVIEW

**Review by tfeher — APPROVED** [review]
Thanks Artem for the fix, just a minor thing, otherwise it looks good to me.

Tagging @enp1s0 for visibility.

**Comment by ahendriksen** [comment]
It looks like this PR increased the binary size of [raft_conda_cpp_cuda11_x86_64.tar.gz](https://downloads.rapids.ai/ci/raft/branch/branch-23.06/2014112/raft_conda_cpp_cuda11_x86_64.tar.gz) by 100MB (from 650MB to 750MB). 
See: 
- This PR: https://downloads.rapids.ai/ci/raft/branch/branch-23.06/2014112/
- Previous PR: https://downloads.rapids.ai/ci/raft/branch/branch-23.06/f60fb79/

Does anybody understand why? It is a significant enough change that might be worth investigating.

**Comment by achirkin** [comment]
The archives contain tests, right? We add two more sets of instantiations to cagra in tests here, which is a lot. Hopefully, https://github.com/rapidsai/raft/pull/1428 will improve this?

**Comment by ahendriksen** [comment]
Ah yes, that makes sense. I also don't see an increase in the wheels. Thanks for pointing out!

**Pull request merged**
