### PR TITLE
Cleaning up cusparse_wrappers

### LINKED ISSUE #289: [BUG] Update cuSparse deprecated calls
**Describe the bug**
Compiling with raft produces the following many wanrings.

```
In file included from /raid/seunghwak/RAPIDS/development/cugraph/cpp/build/_deps/raft-src/cpp/include/raft/handle.hpp:37,
                 from /raid/seunghwak/RAPIDS/development/cugraph/cpp/tests/utilities/device_comm_wrapper.hpp:19,
                 from /raid/seunghwak/RAPIDS/development/cugraph/cpp/tests/experimental/mg_sssp_test.cpp:19:
/raid/seunghwak/RAPIDS/development/cugraph/cpp/build/_deps/raft-src/cpp/include/raft/sparse/cusparse_wrappers.h: In function ‘cusparseStatus_t raft::sparse::cusparsecsrmvex_bufferSize(cusparseHandle_t, cusparseAlgMode_t, cusparseOperation_t, int, int, int, const T*, cusparseMatDescr_t, const T*, const int*, const int*, const T*, const T*, T*, size_t*, cudaStream_t) [with T = float; cusparseHandle_t = cusparseContext*; cusparseMatDescr_t = cusparseMatDescr*; size_t = long unsigned int; cudaStream_t = CUstream_st*]’:
/raid/seunghwak/RAPIDS/development/cugraph/cpp/build/_deps/raft-src/cpp/include/raft/sparse/cusparse_wrappers.h:583:46: warning: ‘cusparseStatus_t cusparseCsrmvEx_bufferSize(cusparseHandle_t, cusparseAlgMode_t, cusparseOperation_t, int, int, int, const void*, cudaDataType, cusparseMatDescr_t, const void*, cudaDataType, const int*, const int*, const void*, cudaDataType, const void*, cudaDataType, void*, cudaDataType, cudaDataType, size_t*)’ is deprecated: please use cusparseSpMV instead [-Wdeprecated-declarations]
  583 |     CUDA_R_32F, CUDA_R_32F, bufferSizeInBytes);
      |                                              ^
In file included from /usr/local/cuda/include/cusolverSp.h:53,
                 from /raid/seunghwak/RAPIDS/development/cugraph/cpp/build/_deps/raft-src/cpp/include/raft/handle.hpp:29,
                 from /raid/seunghwak/RAPIDS/development/cugraph/cpp/tests/utilities/device_comm_wrapper.hpp:19,
                 from /raid/seunghwak/RAPIDS/development/cugraph/cpp/tests/experimental/mg_sssp_test.cpp:19:
/usr/local/cuda/include/cusparse.h:710:1: note: declared here
  710 | cusparseCsrmvEx_bufferSize(cusparseHandle_t         handle,
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /raid/seunghwak/RAPIDS/development/cugraph/cpp/build/_deps/raft-src/cpp/include/raft/handle.hpp:37,
                 from /raid/seunghwak/RAPIDS/development/cugraph/cpp/tests/utilities/device_comm_wrapper.hpp:19,
                 from /raid/seunghwak/RAPIDS/development/cugraph/cpp/tests/experimental/mg_sssp_test.cpp:19:
/raid/seunghwak/RAPIDS/development/cugraph/cpp/build/_deps/raft-src/cpp/include/raft/sparse/cusparse_wrappers.h:583:46: warning: ‘cusparseStatus_t cusparseCsrmvEx_bufferSize(cusparseHandle_t, cusparseAlgMode_t, cusparseOperation_t, int, int, int, const void*, cudaDataType, cusparseMatDescr_t, const void*, cudaDataType, const int*, const int*, const void*, cudaDataType, const void*, cudaDataType, void*, cudaDataType, cudaDataType, size_t*)’ is deprecated: please use cusparseSpMV instead [-Wdeprecated-declarations]
  583 |     CUDA_R_32F, CUDA_R_32F, bufferSizeInBytes);
      |                                              ^
In file included from /usr/local/cuda/include/cusolverSp.h:53,
                 from /raid/seunghwak/RAPIDS/development/cugraph/cpp/build/_deps/raft-src/cpp/include/raft/handle.hpp:29,
                 from /raid/seunghwak/RAPIDS/development/cugraph/cpp/tests/utilities/device_comm_wrapper.hpp:19,
                 from /raid/seunghwak/RAPIDS/development/cugraph/cpp/tests/experimental/mg_sssp_test.cpp:19:
/usr/local/cuda/include/cusparse.h:710:1: note: declared here
  710 | cusparseCsrmvEx_bufferSize(cusparseHandle_t         handle,
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /raid/seunghwak/RAPIDS/development/cugraph/cpp/build/_deps/raft-src/cpp/include/raft/handle.hpp:37,
                 from /raid/seunghwak/RAPIDS/development/cugraph/cpp/tests/utilities/device_comm_wrapper.hpp:19,
                 from /raid/seunghwak/RAPIDS/development/cugraph/cpp/tests/experimental/mg_sssp_test.cpp:19:
/raid/seunghwak/RAPIDS/development/cugraph/cpp/build/_deps/raft-src/cpp/include/raft/sparse/cusparse_wrappers.h: In function ‘cusparseStatus_t raft::sparse::cusparsecsrmvex_bufferSize(cusparseHandle_t, cusparseAlgMode_t, cusparseOperation_t, int, int, int, const T*, cusparseMatDescr_t, const T*, const int*, const int*, const T*, const T*, T*, size_t*, cudaStream_t) [with T = double; cusparseHandle_t = cusparseContext*; cusparseMatDescr_t = cusparseMatDescr*; size_t = long unsigned int; cudaStream_t = CUstream_st*]’:
/raid/seunghwak/RAPIDS/development/cugraph/cpp/build/_deps/raft-src/cpp/include/raft/sparse/cusparse_wrappers.h:596:46: warning: ‘cusparseStatus_t cusparseCsrmvEx_bufferSize(cusparseHandle_t, cusparseAlgMode_t, cusparseOperation_t, int, int, int, const void*, cudaDataType, cusparseMatDescr_t, const void*, cudaDataType, const int*, const int*, const void*, cudaDataType, const void*, cudaDataType, void*, cudaDataType, cudaDataType, size_t*)’ is deprecated: please use cusparseSpMV instead [-Wdeprecated-declarations]
  596 |     CUDA_R_64F, CUDA_R_64F, bufferSizeInBytes);
      |                                              ^
In file included from /usr/local/cuda/include/cusolverSp.h:53,
                 from /raid/seunghwak/RAPIDS/development/cugraph/cpp/build/_deps/raft-src/cpp/include/raft/handle.hpp:29,
                 from /raid/seunghwak/RAPIDS/development/cugraph/cpp/tests/utilities/device_comm_wrapper.hpp:19,
                 from /raid/seunghwak/RAPIDS/development/cugraph/cpp/tests/experimental/mg_sssp_test.cpp:19:
/usr/local/cuda/include/cusparse.h:710:1: note: declared here
  710 | cusparseCsrmvEx_bufferSize(cusparseHandle_t         handle,
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /raid/seunghwak/RAPIDS/development/cugraph/cpp/build/_deps/raft-src/cpp/include/raft/handle.hpp:37,
                 from /raid/seunghwak/RAPIDS/development/cugraph/cpp/tests/utilities/device_comm_wrapper.hpp:19,
                 from /raid/seunghwak/RAPIDS/development/cugraph/cpp/tests/experimental/mg_sssp_test.cpp:19:
/raid/seunghwak/RAPIDS/development/cugraph/cpp/build/_deps/raft-src/cpp/include/raft/sparse/cusparse_wrappers.h:596:46: warning: ‘cusparseStatus_t cusparseCsrmvEx_bufferSize(cusparseHandle_t, cusparseAlgMode_t, cusparseOperation_t, int, int, int, const void*, cudaDataType, cusparseMatDescr_t, const void*, cudaDataType, const int*, const int*, const void*, cudaDataType, const void*, cudaDataType, void*, cudaDataType, cudaDataType, size_t*)’ is deprecated: please use cusparseSpMV instead [-Wdeprecated-declarations]
  596 |     CUDA_R_64F, CUDA_R_64F, bufferSizeInBytes);
      |                                              ^
In file included from /usr/local/cuda/include/cusolverSp.h:53,
                 from /raid/seunghwak/RAPIDS/development/cugraph/cpp/build/_deps/raft-src/cpp/include/raft/handle.hpp:29,
                 from /raid/seunghwak/RAPIDS/development/cugraph/cpp/tests/utilities/device_comm_wrapper.hpp:19,
                 from /raid/seunghwak/RAPIDS/development/cugraph/cpp/tests/experimental/mg_sssp_test.cpp:19:
/usr/local/cuda/include/cusparse.h:710:1: note: declared here
  710 | cusparseCsrmvEx_bufferSize(cusparseHandle_t         handle,
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /raid/seunghwak/RAPIDS/development/cugraph/cpp/build/_deps/raft-src/cpp/include/raft/handle.hpp:37,
                 from /raid/seunghwak/RAPIDS/development/cugraph/cpp/tests/utilities/device_comm_wrapper.hpp:19,
                 from /raid/seunghwak/RAPIDS/development/cugraph/cpp/tests/experimental/mg_sssp_test.cpp:19:
/raid/seunghwak/RAPIDS/development/cugraph/cpp/build/_deps/raft-src/cpp/include/raft/sparse/cusparse_wrappers.h: In function ‘cusparseStatus_t raft::sparse::cusparsecsrmvex(cusparseHandle_t, cusparseAlgMode_t, cusparseOperation_t, int, int, int, const T*, cusparseMatDescr_t, const T*, const int*, const int*, const T*, const T*, T*, T*, cudaStream_t) [with T = float; cusparseHandle_t = cusparseContext*; cusparseMatDescr_t = cusparseMatDescr*; cudaStream_t = CUstream_st*]’:
/raid/seunghwak/RAPIDS/development/cugraph/cpp/build/_deps/raft-src/cpp/include/raft/sparse/cusparse_wrappers.h:616:44: warning: ‘cusparseStatus_t cusparseCsrmvEx(cusparseHandle_t, cusparseAlgMode_t, cusparseOperation_t, int, int, int, const void*, cudaDataType, cusparseMatDescr_t, const void*, cudaDataType, const int*, const int*, const void*, cudaDataType, const void*, cudaDataType, void*, cudaDataType, cudaDataType, void*)’ is deprecated: please use cusparseSpMV instead [-Wdeprecated-declarations]
  616 |                          CUDA_R_32F, buffer);
      |                                            ^
In file included from /usr/local/cuda/include/cusolverSp.h:53,
                 from /raid/seunghwak/RAPIDS/development/cugraph/cpp/build/_deps/raft-src/cpp/include/raft/handle.hpp:29,
                 from /raid/seunghwak/RAPIDS/development/cugraph/cpp/tests/utilities/device_comm_wrapper.hpp:19,
                 from /raid/seunghwak/RAPIDS/development/cugraph/cpp/tests/experimental/mg_sssp_test.cpp:19:
/usr/local/cuda/include/cusparse.h:734:1: note: declared here
  734 | cusparseCsrmvEx(cusparseHandle_t         handle,
      | ^~~~~~~~~~~~~~~
In file included from /raid/seunghwak/RAPIDS/development/cugraph/cpp/build/_deps/raft-src/cpp/include/raft/handle.hpp:37,
                 from /raid/seunghwak/RAPIDS/development/cugraph/cpp/tests/utilities/device_comm_wrapper.hpp:19,
                 from /raid/seunghwak/RAPIDS/development/cugraph/cpp/tests/experimental/mg_sssp_test.cpp:19:
/raid/seunghwak/RAPIDS/development/cugraph/cpp/build/_deps/raft-src/cpp/include/raft/sparse/cusparse_wrappers.h:616:44: warning: ‘cusparseStatus_t cusparseCsrmvEx(cusparseHandle_t, cusparseAlgMode_t, cusparseOperation_t, int, int, int, const void*, cudaDataType, cusparseMatDescr_t, const void*, cudaDataType, const int*, const int*, const void*, cudaDataType, const void*, cudaDataType, void*, cudaDataType, cudaDataType, void*)’ is deprecated: please use cusparseSpMV instead [-Wdeprecated-declarations]
  616 |                          CUDA_R_32F, buffer);
      |                                            ^
In file included from /usr/local/cuda/include/cusolverSp.h:53,
                 from /raid/seunghwak/RAPIDS/development/cugraph/cpp/build/_deps/raft-src/cpp/include/raft/handle.hpp:29,
                 from /raid/seunghwak/RAPIDS/development/cugraph/cpp/tests/utilities/device_comm_wrapper.hpp:19,
                 from /raid/seunghwak/RAPIDS/development/cugraph/cpp/tests/experimental/mg_sssp_test.cpp:19:
/usr/local/cuda/include/cusparse.h:734:1: note: declared here
  734 | cusparseCsrmvEx(cusparseHandle_t         handle,
      | ^~~~~~~~~~~~~~~
In file included from /raid/seunghwak/RAPIDS/development/cugraph/cpp/build/_deps/raft-src/cpp/include/raft/handle.hpp:37,
                 from /raid/seunghwak/RAPIDS/development/cugraph/cpp/tests/utilities/device_comm_wrapper.hpp:19,
                 from /raid/seunghwak/RAPIDS/development/cugraph/cpp/tests/experimental/mg_sssp_test.cpp:19:
/raid/seunghwak/RAPIDS/development/cugraph/cpp/build/_deps/raft-src/cpp/include/raft/sparse/cusparse_wrappers.h: In function ‘cusparseStatus_t raft::sparse::cusparsecsrmvex(cusparseHandle_t, cusparseAlgMode_t, cusparseOperation_t, int, int, int, const T*, cusparseMatDescr_t, const T*, const int*, const int*, const T*, const T*, T*, T*, cudaStream_t) [with T = double; cusparseHandle_t = cusparseContext*; cusparseMatDescr_t = cusparseMatDescr*; cudaStream_t = CUstream_st*]’:
/raid/seunghwak/RAPIDS/development/cugraph/cpp/build/_deps/raft-src/cpp/include/raft/sparse/cusparse_wrappers.h:629:44: warning: ‘cusparseStatus_t cusparseCsrmvEx(cusparseHandle_t, cusparseAlgMode_t, cusparseOperation_t, int, int, int, const void*, cudaDataType, cusparseMatDescr_t, const void*, cudaDataType, const int*, const int*, const void*, cudaDataType, const void*, cudaDataType, void*, cudaDataType, cudaDataType, void*)’ is deprecated: please use cusparseSpMV instead [-Wdeprecated-declarations]
  629 |                          CUDA_R_64F, buffer);
      |                                            ^
In file included from /usr/local/cuda/include/cusolverSp.h:53,
                 from /raid/seunghwak/RAPIDS/development/cugraph/cpp/build/_deps/raft-src/cpp/include/raft/handle.hpp:29,
                 from /raid/seunghwak/RAPIDS/development/cugraph/cpp/tests/utilities/device_comm_wrapper.hpp:19,
                 from /raid/seunghwak/RAPIDS/development/cugraph/cpp/tests/experimental/mg_sssp_test.cpp:19:
/usr/local/cuda/include/cusparse.h:734:1: note: declared here
  734 | cusparseCsrmvEx(cusparseHandle_t         handle,
      | ^~~~~~~~~~~~~~~
In file included from /raid/seunghwak/RAPIDS/development/cugraph/cpp/build/_deps/raft-src/cpp/include/raft/handle.hpp:37,
                 from /raid/seunghwak/RAPIDS/development/cugraph/cpp/tests/utilities/device_comm_wrapper.hpp:19,
                 from /raid/seunghwak/RAPIDS/development/cugraph/cpp/tests/experimental/mg_sssp_test.cpp:19:
/raid/seunghwak/RAPIDS/development/cugraph/cpp/build/_deps/raft-src/cpp/include/raft/sparse/cusparse_wrappers.h:629:44: warning: ‘cusparseStatus_t cusparseCsrmvEx(cusparseHandle_t, cusparseAlgMode_t, cusparseOperation_t, int, int, int, const void*, cudaDataType, cusparseMatDescr_t, const void*, cudaDataType, const int*, const int*, const void*, cudaDataType, const void*, cudaDataType, void*, cudaDataType, cudaDataType, void*)’ is deprecated: please use cusparseSpMV instead [-Wdeprecated-declarations]
  629 |                          CUDA_R_64F, buffer);
      |                                            ^
In file included from /usr/local/cuda/include/cusolverSp.h:53,
                 from /raid/seunghwak/RAPIDS/development/cugraph/cpp/build/_deps/raft-src/cpp/include/raft/handle.hpp:29,
                 from /raid/seunghwak/RAPIDS/development/cugraph/cpp/tests/utilities/device_comm_wrapper.hpp:19,
                 from /raid/seunghwak/RAPIDS/development/cugraph/cpp/tests/experimental/mg_sssp_test.cpp:19:
/usr/local/cuda/include/cusparse.h:734:1: note: declared here
  734 | cusparseCsrmvEx(cusparseHandle_t         handle,
      | ^~~~~~~~~~~~~~~
In file included from /raid/seunghwak/RAPIDS/development/cugraph/cpp/build/_deps/raft-src/cpp/include/raft/handle.hpp:37,
                 from /raid/seunghwak/RAPIDS/development/cugraph/cpp/tests/utilities/device_comm_wrapper.hpp:19,
                 from /raid/seunghwak/RAPIDS/development/cugraph/cpp/tests/experimental/mg_sssp_test.cpp:19:
/raid/seunghwak/RAPIDS/development/cugraph/cpp/build/_deps/raft-src/cpp/include/raft/sparse/cusparse_wrappers.h: In function ‘cusparseStatus_t raft::sparse::cusparsecsr2dense(cusparseHandle_t, int, int, cusparseMatDescr_t, const T*, const int*, const int*, T*, int, cudaStream_t) [with T = float; cusparseHandle_t = cusparseContext*; cusparseMatDescr_t = cusparseMatDescr*; cudaStream_t = CUstream_st*]’:
/raid/seunghwak/RAPIDS/development/cugraph/cpp/build/_deps/raft-src/cpp/include/raft/sparse/cusparse_wrappers.h:852:47: warning: ‘cusparseStatus_t cusparseScsr2dense(cusparseHandle_t, int, int, cusparseMatDescr_t, const float*, const int*, const int*, float*, int)’ is deprecated: please use cusparseSparseToDense instead [-Wdeprecated-declarations]
  852 |                             csrColIndA, A, lda);
      |                                               ^
In file included from /usr/local/cuda/include/cusolverSp.h:53,
                 from /raid/seunghwak/RAPIDS/development/cugraph/cpp/build/_deps/raft-src/cpp/include/raft/handle.hpp:29,
                 from /raid/seunghwak/RAPIDS/development/cugraph/cpp/tests/utilities/device_comm_wrapper.hpp:19,
                 from /raid/seunghwak/RAPIDS/development/cugraph/cpp/tests/experimental/mg_sssp_test.cpp:19:
/usr/local/cuda/include/cusparse.h:4098:1: note: declared here
 4098 | cusparseScsr2dense(cusparseHandle_t         handle,
      | ^~~~~~~~~~~~~~~~~~
In file included from /raid/seunghwak/RAPIDS/development/cugraph/cpp/build/_deps/raft-src/cpp/include/raft/handle.hpp:37,
                 from /raid/seunghwak/RAPIDS/development/cugraph/cpp/tests/utilities/device_comm_wrapper.hpp:19,
                 from /raid/seunghwak/RAPIDS/development/cugraph/cpp/tests/experimental/mg_sssp_test.cpp:19:
/raid/seunghwak/RAPIDS/development/cugraph/cpp/build/_deps/raft-src/cpp/include/raft/sparse/cusparse_wrappers.h:852:47: warning: ‘cusparseStatus_t cusparseScsr2dense(cusparseHandle_t, int, int, cusparseMatDescr_t, const float*, const int*, const int*, float*, int)’ is deprecated: please use cusparseSparseToDense instead [-Wdeprecated-declarations]
  852 |                             csrColIndA, A, lda);
      |                                               ^
In file included from /usr/local/cuda/include/cusolverSp.h:53,
                 from /raid/seunghwak/RAPIDS/development/cugraph/cpp/build/_deps/raft-src/cpp/include/raft/handle.hpp:29,
                 from /raid/seunghwak/RAPIDS/development/cugraph/cpp/tests/utilities/device_comm_wrapper.hpp:19,
                 from /raid/seunghwak/RAPIDS/development/cugraph/cpp/tests/experimental/mg_sssp_test.cpp:19:
/usr/local/cuda/include/cusparse.h:4098:1: note: declared here
 4098 | cusparseScsr2dense(cusparseHandle_t         handle,
      | ^~~~~~~~~~~~~~~~~~
In file included from /raid/seunghwak/RAPIDS/development/cugraph/cpp/build/_deps/raft-src/cpp/include/raft/handle.hpp:37,
                 from /raid/seunghwak/RAPIDS/development/cugraph/cpp/tests/utilities/device_comm_wrapper.hpp:19,
                 from /raid/seunghwak/RAPIDS/development/cugraph/cpp/tests/experimental/mg_sssp_test.cpp:19:
/raid/seunghwak/RAPIDS/development/cugraph/cpp/build/_deps/raft-src/cpp/include/raft/sparse/cusparse_wrappers.h: In function ‘cusparseStatus_t raft::sparse::cusparsecsr2dense(cusparseHandle_t, int, int, cusparseMatDescr_t, const T*, const int*, const int*, T*, int, cudaStream_t) [with T = double; cusparseHandle_t = cusparseContext*; cusparseMatDescr_t = cusparseMatDescr*; cudaStream_t = CUstream_st*]’:
/raid/seunghwak/RAPIDS/development/cugraph/cpp/build/_deps/raft-src/cpp/include/raft/sparse/cusparse_wrappers.h:863:47: warning: ‘cusparseStatus_t cusparseDcsr2dense(cusparseHandle_t, int, int, cusparseMatDescr_t, const double*, const int*, const int*, double*, int)’ is deprecated: please use cusparseSparseToDense instead [-Wdeprecated-declarations]
  863 |                             csrColIndA, A, lda);
      |                                               ^
In file included from /usr/local/cuda/include/cusolverSp.h:53,
                 from /raid/seunghwak/RAPIDS/development/cugraph/cpp/build/_deps/raft-src/cpp/include/raft/handle.hpp:29,
                 from /raid/seunghwak/RAPIDS/development/cugraph/cpp/tests/utilities/device_comm_wrapper.hpp:19,
                 from /raid/seunghwak/RAPIDS/development/cugraph/cpp/tests/experimental/mg_sssp_test.cpp:19:
/usr/local/cuda/include/cusparse.h:4110:1: note: declared here
 4110 | cusparseDcsr2dense(cusparseHandle_t         handle,
      | ^~~~~~~~~~~~~~~~~~
In file included from /raid/seunghwak/RAPIDS/development/cugraph/cpp/build/_deps/raft-src/cpp/include/raft/handle.hpp:37,
                 from /raid/seunghwak/RAPIDS/development/cugraph/cpp/tests/utilities/device_comm_wrapper.hpp:19,
                 from /raid/seunghwak/RAPIDS/development/cugraph/cpp/tests/experimental/mg_sssp_test.cpp:19:
/raid/seunghwak/RAPIDS/development/cugraph/cpp/build/_deps/raft-src/cpp/include/raft/sparse/cusparse_wrappers.h:863:47: warning: ‘cusparseStatus_t cusparseDcsr2dense(cusparseHandle_t, int, int, cusparseMatDescr_t, const double*, const int*, const int*, double*, int)’ is deprecated: please use cusparseSparseToDense instead [-Wdeprecated-declarations]
  863 |                             csrColIndA, A, lda);
      |                                               ^
In file included from /usr/local/cuda/include/cusolverSp.h:53,
                 from /raid/seunghwak/RAPIDS/development/cugraph/cpp/build/_deps/raft-src/cpp/include/raft/handle.hpp:29,
                 from /raid/seunghwak/RAPIDS/development/cugraph/cpp/tests/utilities/device_comm_wrapper.hpp:19,
                 from /raid/seunghwak/RAPIDS/development/cugraph/cpp/tests/experimental/mg_sssp_test.cpp:19:
/usr/local/cuda/include/cusparse.h:4110:1: note: declared here
 4110 | cusparseDcsr2dense(cusparseHandle_t         handle,
      | ^~~~~~~~~~~~~~~~~~
```

### PR DESCRIPTION
**Pull request by cjnolet**
Closes #289

### CODE REVIEW

**Review by trivialfis — APPROVED** [review]
Always feels good to see code being removed. ;-)

**Comment by cjnolet** [comment]
Functions throwing deprecation warnings in cugraph CI: cusparseCsrmvEx, cusparseCsrmvEx_bufferSize, cusparseDcsr2dense, cusparseScsr2dense

**Review by ChuckHastings — APPROVED** [review]
!!!!

**Review by seunghwak — APPROVED** [review]
Thanks a lot!!!!

**Comment by cjnolet** [comment]
rerun tests

**Comment by cjnolet** [comment]
@gpucibot merge

**Pull request merged**
