### PR TITLE
bump NCCL floor to 2.19

### PR DESCRIPTION
**Pull request by jameslamb**
Follow-up to #2443

As part of the work to support NumPy 2 across RAPIDS, we found reason to upgrade some libraries like `cugraph` to slightly newer NCCL (`>=2.19`). Context: https://github.com/rapidsai/build-planning/issues/102#issuecomment-2375595743

This applies that same bump here, to keep the range of NCCL versions consistent across RAPIDS.

### CODE REVIEW

**Review by jakirkham — APPROVED** [review]
Thanks James! 🙏

**Comment by jakirkham** [comment]
One build failed with a networking error. Will wait for the rest of the builds to complete and then restart

**Comment by jameslamb** [comment]
@jakirkham I just cancelled CI and restarted the failed jobs.

`conda-cpp-build` is upstream of a lot of other jobs, including `conda-cpp-tests` which can take 2-3 hours to run 😬 

I know we're getting very close to code freeze... will leave it to @cjnolet 's discretion whether to admin-merge at some point or to wait for all those test jobs to run. I think we can be highly confident that this will work, given that the tests were all already using NCCL 2.22 on this previous successful run: https://github.com/rapidsai/raft/actions/runs/11040960166/job/30673327293

(and should continue to, given that this just moves the floor from `>=2.18` to `>=2.19`)

**Comment by jakirkham** [comment]
Sounds good. Thanks James! 🙏

Have also mentioned this PR in the release thread offline. So it is being tracked there

**Review by cjnolet — APPROVED** [review]

**Comment by jakirkham** [comment]
Thanks James and Corey! 🙏

**Pull request merged**
