### PR TITLE
Build CUDA 12 packages of libraft

### PR DESCRIPTION
**Pull request by bdice**
This is an experiment to build `libraft` conda packages using CUDA 12 from the `nvidia` channel.

To-do:
- [ ] Figure out how to pull librmm CUDA 12 conda packages from upstream?
- [ ] ...

**Do not merge this PR.**

### CODE REVIEW

**Comment by cjnolet** [comment]
@bdice you should be able to manually pin the branch that consolidates the libraft artifacts in this PR and then you can test against the real deal. https://github.com/cjnolet/raft/tree/fea-2304-remove-nn-lib

**Comment by bdice** [comment]
Closing in favor of #1388 -- but @vyasr can you please rename that PR to match this PR's name? We are tracking these names in a project board and making them consistent would be nice.

**Comment by vyasr** [comment]
Sure, will do. I would have pushed directly to your branch but I had done enough rebasing for one day and didn't feel like resolving merge conflicts again.

**Comment by vyasr** [comment]
Do I need to update any project board manually?

**Comment by bdice** [comment]
> Do I need to update any project board manually?

I took care of it.

**Pull request closed without merging**
