### PR TITLE
Consolidate Python conda recipes

### PR DESCRIPTION
**Pull request by Ethyling**

### CODE REVIEW

**Comment by cjnolet** [comment]
@Ethyling is this ready for review? It looks like it's waiting on a code-owner from ops to review it.

**Comment by Ethyling** [comment]
> @Ethyling is this ready for review? It looks like it's waiting on a code-owner from ops to review it.

This PR is blocked by a bug in Conda. I need to take some time to test it again before merging. I'm moving it as a draft for now. Sorry for the noise

**Comment by cjnolet** [comment]
rerun tests

**Comment by Ethyling** [comment]
Closing for now. A bug in conda is preventing doing this

**Pull request closed without merging**
