### PR TITLE
Unpin `dask` & `distributed` in CI

### PR DESCRIPTION
**Pull request by galipremsagar**
Changes to be in-line with: https://github.com/rapidsai/cudf/pull/9307/

### CODE REVIEW

**Review by ajschmidt8 — APPROVED** [review]

**Comment by galipremsagar** [comment]
@gpucibot merge

**Comment by ajschmidt8** [comment]
@gpucibot merge

**Comment by ajschmidt8** [comment]
@galipremsagar, it looks like you only have `read` permissions on this repo which is why the comment didn't work for you

**Comment by galipremsagar** [comment]
@ajschmidt8 , Hmmm, but I opened a request last week asking for traige access to the following repos: https://github.com/rapidsai/ops/issues/1822

Could you see where the problem could be when you get time?

**Pull request merged**
