### PR TITLE
Add lds and sts inline ptx instructions to force vector instruction generation

### PR DESCRIPTION
**Pull request by mdoijade**
Adds inline ptx assembly for lds & sts instructions for float, float2, float4, double, double2.
This ensures that compiler doesn't mistakenly generate non-vectorized instructions whenever we need it to generate vectorized version.
Also this ensures that we always generate non-generic ld/st instructions eliminating compiler from generating generic ld/st instructions.
These functions now requires the given shmem pointer should be aligned by the vector length, like for float4 lds/sts shmem pointer should be aligned by 16 bytes else it might silently fail or can also give runtime error.

### CODE REVIEW

**Comment by teju85** [comment]
@mdoijade did you get a chance to check whether this change causes any perf regressions, especially in the distance prims? (asking because AFAIK, they are only ones who are using these methods in their kernels)

**Comment by teju85** [comment]
rerun tests

**Review by teju85 — APPROVED** [review]
Changes LGTM

**Comment by mdoijade** [comment]
@teju85 can we merge this PR now? btw the above failure in "gpuCI/raft/gpu/cuda/11.0/python/3.7/ubuntu16.04" is CI docker installation issue.

**Comment by teju85** [comment]
@dantegd can we get some help in getting the CI passed for this PR, please?

**Comment by teju85** [comment]
rerun tests

**Comment by mdoijade** [comment]
@teju85 can we merge this now?

**Comment by teju85** [comment]
@gpucibot merge

**Pull request merged**
