### PR TITLE
Replace `ccache` with `sccache`

### PR DESCRIPTION
**Pull request by ajschmidt8**
This PR replaces `ccache` with `sccache`.

### CODE REVIEW

**Review by AyodeAwe — APPROVED** [review]
LGTM

**Comment by ajschmidt8** [comment]
rerun tests

**Comment by ajschmidt8** [comment]
rerun tests

**Comment by ajschmidt8** [comment]
pre-cache build - https://gpuci.gpuopenanalytics.com/job/rapidsai/job/gpuci/job/raft/job/prb/job/raft-prb/1573/

**Comment by ajschmidt8** [comment]
rerun tests

**Comment by ajschmidt8** [comment]
PR is ready for review, but we'll wait to merge until all the other PRs are confirmed working as well.

**Review by raydouglass — APPROVED** [review]

**Comment by ajschmidt8** [comment]
@gpucibot merge

**Pull request merged**
