### PR TITLE
Pass stream to device_scalar::value() calls.

### PR DESCRIPTION
**Pull request by harrism**
In comms/test.hpp `device_scalar::value` was not being passed an explicit stream, which means that the default stream was being synced. rapidsai/rmm#789 will remove the default from this parameter, and would have therefore broken the RAFT build. So this PR fixes the oversynchronization and ensures RAFT will build after the RMM PR is merged.

Note this PR includes the cmake changes from #258 (just so I could build locally). Once #258 is merged this PR's changes will be simplified.

### CODE REVIEW

**Review by dantegd — APPROVED** [review]
Changes look good to me, same comment about merging 21.08 so CI passes

**Comment by harrism** [comment]
> Changes look good to me, same comment about merging 21.08 so CI passes

Done.

**Review by ChuckHastings — APPROVED** [review]

**Comment by harrism** [comment]
@gpucibot merge

**Comment by harrism** [comment]
I don't think I can merge.

**Comment by ajschmidt8** [comment]
@gpucibot merge

**Pull request merged**
