### PR TITLE
Adding distance specializations

### PR DESCRIPTION
**Pull request by cjnolet**
This adds new export targets for distance specializations that speed up building and re-building by 1) increasing parallelism / compilation units, and 2) reuses compiled object files across different compilation units.

### CODE REVIEW

**Comment by ajschmidt8** [comment]
@cjnolet, should this be targeting `22.02`?

**Review by divyegala — APPROVED** [review]
Looks great!

**Comment by cjnolet** [comment]
rerun tests

**Comment by cjnolet** [comment]
@gpucibot merge

**Pull request merged**
