### PR TITLE
[FEA] Add distance epilogue for NN Descent

### PR DESCRIPTION
**Pull request by jinsolp**
Adding distance epilogue to NN Descent.
Planning to use them for the following use cases as of now;
- Calculating mutual reachability distance for HDBSCAN (possibly for usage with HDBSCAN - [related PR here](https://github.com/rapidsai/cuml/pull/5939))
- Enabling `L2SqrtExpanded` distance metric, by `sqrt`-ing the current supported metric (`L2Expanded`) of NN Descent in the distance epilogue. (for usage with UMAP - [related PR here](https://github.com/rapidsai/cuml/pull/5910))

### CODE REVIEW

**Review by tarang-jain — CHANGES_REQUESTED** [review]
LGTM! Just a minor suggestion.

**Review by tarang-jain — APPROVED** [review]

**Review by tfeher — APPROVED** [review]
Thanks @jinsolp for the PR, it looks good to me!

The only issue is that we are moving nearest neighbor code to cuVS, I have added a note to #170 to track this.

**Comment by jinsolp** [comment]
Thank you ☺️

**Review by divyegala — APPROVED** [review]

**Pull request merged**
