### PR TITLE
Reusing shared libs in gpu ci builds

### PR DESCRIPTION
**Pull request by cjnolet**

### CODE REVIEW

**Review by dantegd — APPROVED** [review]

**Review by msadang — APPROVED** [review]
LGTM

**Review by ajschmidt8 — APPROVED** [review]

**Comment by cjnolet** [comment]
rerun tests

**Comment by cjnolet** [comment]
rerun tests

**Comment by cjnolet** [comment]
@achirkin the cuda 11.0 CI appears to be consistently hanging on new meanvar tests. I've been able to reproduce this over several runs of the gtests now. Could this be the from the atomicCAS?

**Comment by achirkin** [comment]
> @achirkin the cuda 11.0 CI appears to be consistently hanging on new meanvar tests. I've been able to reproduce this over several runs of the gtests now. Could this be the from the atomicCAS?

My apologies! I've had hard time trying to reproduce it locally, but hopefully PR https://github.com/rapidsai/raft/pull/489 will fix this.

**Comment by cjnolet** [comment]
@gpucibot merge

**Pull request merged**
