### PR TITLE
Update get_rmm.cmake to better support CalVer

### PR DESCRIPTION
**Pull request by harrism**
Updates raft's get_rmm.cmake logic to work like cuML and cuGraph, so that it works better with CalVer. This helps when building RAPIDS libraries locally and depending on a local RMM (e.g. with rapids-compose).

### CODE REVIEW

**Review by dantegd — APPROVED** [review]
Lgtm, just needs to merge 21.08 into the PR so it gets the fixes of #253

**Comment by harrism** [comment]
> Lgtm, just needs to merge 21.08 into the PR so it gets the fixes of #253

Done

**Comment by dantegd** [comment]
@gpucibot merge

**Comment by dantegd** [comment]
@gpucibot merge

**Pull request merged**
