### PR TITLE
[WIP] Test  CI issues 

### PR DESCRIPTION
**Pull request by VibhuJawa**

### CODE REVIEW

**Comment by cjnolet** [comment]
Looks like it's still skipping the tests. Darn. Tomorrow I'll attempt removing the conditional testing skipping based on the exception catching and see if it might be a dependency issue. Perhaps its also possible a dependency changed recently and maybe it was just coincidence it was around the time your changes were merged.

**Comment by VibhuJawa** [comment]
@cjnolet , I think the issue was due to `__init__.py` and we are running into below.    I am still trying to think what a long term good fix will be and why we are running into this problem. 

```
    from raft_dask.common import (
common/__init__.py:16: in <module>
    from .comms import Comms, local_handle
common/comms.py:28: in <module>
    from .comms_utils import (
E   ModuleNotFoundError: No module named 'raft_dask.common.comms_utils'
```

**Review by cjnolet — APPROVED** [review]
Thanks again for finding/fixing this, @VibhuJawa!

**Pull request merged**
