### PR TITLE
Update cuco version

### PR DESCRIPTION
**Pull request by vyasr**
This updates cuco to the latest version used in cudf.

### CODE REVIEW

**Review by robertmaynard — APPROVED** [review]

**Review by cjnolet — CHANGES_REQUESTED** [review]
Holding this from being merged until cugraph is ready.

**Review by ChuckHastings — APPROVED** [review]

**Review by cjnolet — APPROVED** [review]

**Comment by cjnolet** [comment]
rerun tests

**Comment by vyasr** [comment]
> rerun tests

See you tomorrow...

**Comment by cjnolet** [comment]
@vyasr not sure if you saw but there was a failure from a flaky test so I restarted it.

**Comment by cjnolet** [comment]
@gpucibot merge

**Pull request merged**
