### PR TITLE
Allow nullptr as input-indices argument of select_k

### PR DESCRIPTION
**Pull request by achirkin**
Allow passing `nullptr` as the input-indices-argument of `select_k`. This would imply the input indices are a range from `0` to `input_len - 1` and improve the performance by doing less global memory reads.

Also makes input pointers `const` as they should be.

### CODE REVIEW

**Comment by achirkin** [comment]
Note, the tests are expected to fail until https://github.com/rapidsai/raft/pull/606 is merged.

**Comment by cjnolet** [comment]
rerun tests

**Review by tfeher — APPROVED** [review]
Thanks Artem for the PR, it looks good to me.

**Comment by achirkin** [comment]
rerun tests

**Comment by cjnolet** [comment]
@gpucibot merge

**Pull request merged**
