### PR TITLE
[REVIEW] Use gtest conda package in CMake/build.sh by default

### PR DESCRIPTION
**Pull request by dantegd**

### CODE REVIEW

**Comment by GPUtester** [comment]
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

**Comment by dantegd** [comment]
@cjnolet because this is in RAFT ant that is in cuML repo?

**Comment by cjnolet** [comment]
I believe there was a trivial change you had asked for that I was unfortunately not able to make before having to take unexpected leave.

**Comment by dantegd** [comment]
@cjnolet yeah indeed, and CI in cuML hasn't been blocked so the change in that repo can wait. But in the RAFT repo (this one), CI is blocked due to this

**Comment by cjnolet** [comment]
@dantegd my bad! This is what I get for trying to Github on my phone!

**Comment by teju85** [comment]
JFYI, I left a comment about `BUILD_GTEST` feature in the main cuML PR https://github.com/rapidsai/cuml/pull/2631.

**Pull request merged**
