### PR TITLE
Sparse KNN improvements

### PR DESCRIPTION
**Pull request by viclafargue**
Answers #1187

### CODE REVIEW

**Comment by cjnolet** [comment]
@viclafargue this is a breaking change for users downstream. Do we have a corresponding PR w/ cuML to test these changes?

**Comment by cjnolet** [comment]
@viclafargue how are we feeling about these changes for 23.06?

**Comment by viclafargue** [comment]
> @viclafargue how are we feeling about these changes for 23.06?

The PR would need a bit more work at the moment. I don't know if it could be part of 23.06.

**Comment by cjnolet** [comment]
@viclafargue, sounds good, I'll push to 23.08.

**Pull request closed without merging**
