### PR TITLE
Fix compilation error when _CLK_BREAKDOWN is defined in cagra.

### PR DESCRIPTION
**Pull request by jiangyinzuo**
PR #1740 forgot to rename `BLOCK_SIZE` in `#ifdef _CLK_BREAKDOWN` blocks.

The use of `RAFT_LOG_DEBUG` in kernel function results in compilation
errors, replace it with `printf`.

Also remove an unused function in search_single_cta_kernel-inl.cuh

After merging:

- [x] port to cuVS https://github.com/rapidsai/cuvs/pull/202

### CODE REVIEW

**Comment by jiangyinzuo** [comment]
Hello @enp1s0 , can you please review this PR and add labels for Label Checker CI?

**Review by enp1s0 — APPROVED** [review]
Thank you @jiangyinzuo for the PR. It looks good to me. Sorry for forgetting to update the clock measurement code in my previous PR.

**Comment by enp1s0** [comment]
@cjnolet Can you run the CI?

**Comment by jiangyinzuo** [comment]
@tfeher I fixed the code style error reported by `ci/check_style.sh`. Can you help me rerun the CI?

**Review by tfeher — APPROVED** [review]
Thanks @jiangyinzuo for the fix, the PR looks good to me.

**Comment by jiangyinzuo** [comment]
```
[ RUN      ] GPUSpan.FromOther
unknown file: Failure
C++ exception with description "parallel_for failed: cudaErrorInvalidDevice: invalid device ordinal" thrown in the test body.
```

Is the failure related to this PR?

**Comment by cjnolet** [comment]
@tfeher @enp1s0 will we also need to port this patch forward to cuVS or does this issue not apply to cuVS?

**Comment by enp1s0** [comment]
@cjnolet Yes, it is needed. As mentioned in the PR description, this PR will be ported to cuVS after this PR is merged.

**Comment by jiangyinzuo** [comment]
I have created a PR for cuvs, see https://github.com/rapidsai/cuvs/pull/202

**Pull request merged**
