### PR TITLE
[REVIEW] Const raft handle in sparse bfknn

### PR DESCRIPTION
**Pull request by cjnolet**

### CODE REVIEW

**Comment by cjnolet** [comment]
cc @trxcllnt

**Review by dantegd — APPROVED** [review]

**Comment by cjnolet** [comment]
@gpucibot merge

**Review by afender — APPROVED** [review]

**Comment by trxcllnt** [comment]
Builds for me locally :+1:

**Review by trxcllnt — APPROVED** [review]

**Comment by cjnolet** [comment]
@gpucibot merge

**Pull request merged**
