### PR TITLE
add half/bfloat support to myInf and abs

### PR DESCRIPTION
**Pull request by Kh4ster**
This PR adds support to __half and nb_bfloat16 to abs and myinf

### CODE REVIEW

**Comment by cjnolet** [comment]
@Kh4ster this PR has been open for awhile. Do you plan to finish this contribution or should we close the PR?

**Comment by Kh4ster** [comment]
@cjnolet Very sorry I was sure this PR had been merged 7 months ago, I will fix it and hopefully we can merge it

**Comment by Kh4ster** [comment]
@cjnolet Should I retarget this to the 24.02 ?

**Review by cjnolet — APPROVED** [review]

**Pull request merged**
