### PR TITLE
Update builds for CUDA `11.8` and Python `3.10`

### PR DESCRIPTION
**Pull request by ajschmidt8**
This PR updates the `raft` CI workflows to build against the CUDA `11.8` / Python `3.10` [branch](https://github.com/rapidsai/shared-action-workflows/tree/cuda-118) of the `shared-action-workflows` repository.

### CODE REVIEW

**Comment by bdice** [comment]
This PR is blocked until we can get ARM + CUDA builds of `faiss` version 1.7.1 or newer (see here: https://github.com/conda-forge/faiss-split-feedstock/pull/58) or remove the `faiss` dependency entirely (several open issues, including #798, #799, #803, ...).

The existing ARM + CUDA builds of `faiss` 1.7.0 do not support GPU architectures newer than 80, which we need to support (86 and 90).

**Comment by jakirkham** [comment]
PR ( https://github.com/conda-forge/faiss-split-feedstock/pull/58 ) added ARM builds (without CUDA). So just CPU builds. That said, this does seem to cover the changes we had in other places before. Though please double check that.

PR ( https://github.com/conda-forge/faiss-split-feedstock/pull/62 ) adds CUDA builds. Based on Bradley's comment above, think we should check that the recipe is doing what we want with [CUDA arches]( https://github.com/conda-forge/faiss-split-feedstock/blob/1c7f8991c3fd09fe520eac0f14438e679ac62ab7/recipe/build-lib.sh#L14-L15 ). There is a second point about build time, which I've outlined in more detail in comment ( https://github.com/conda-forge/faiss-split-feedstock/pull/62#issuecomment-1374307900 ). Feel free to raise anything else I've missed in that PR.

**Review by bdice — APPROVED** [review]

**Review by raydouglass — APPROVED** [review]

**Review by AyodeAwe — APPROVED** [review]

**Review by cjnolet — APPROVED** [review]
Thank you for also updating the build docs!

**Pull request merged**
