### PR TITLE
[Opt] Enforce the UT Coverity and add benchmark for `transpose`

### PR DESCRIPTION
**Pull request by rhdong**

### CODE REVIEW

**Comment by rhdong** [comment]
- Reopen for https://github.com/rapidsai/raft/pull/2421 for wrongly forced push

**Review by achirkin — APPROVED** [review]

**Comment by cjnolet** [comment]
This needs to go through proper benchmarking and review. I think we should push this to 24.12 in the interest of time.

**Review by cjnolet — APPROVED** [review]

**Pull request merged**
