### PR TITLE
Fix components installation

### PR DESCRIPTION
**Pull request by Ethyling**
We need to install the `raft-${comp}-dependencies.cmake` files as part of the `raft` component

### CODE REVIEW

**Comment by vyasr** [comment]
Perhaps a naive question, but should we be using `rapids_export` from `rapids-cmake` instead of `raft_export`?

**Comment by robertmaynard** [comment]
> Perhaps a naive question, but should we be using `rapids_export` from `rapids-cmake` instead of `raft_export`?

Not currently, as rapids_export isn't aware of components

**Comment by cjnolet** [comment]
Is this one superseded by #653? If so, can we close this?

**Comment by Ethyling** [comment]
> Is this one superseded by #653? If so, can we close this?

Yes, we can close this

**Pull request closed without merging**
