### PR TITLE
Update select-k heuristic

### PR DESCRIPTION
**Pull request by benfred**
With https://github.com/rapidsai/raft/pull/1878 merged, the performance of the radix select algorithms is much improved and we no longer need to incorporate the faiss block select algorithm. With #1878 merged, faiss block select goes from being the 3rd ranked selection algorithm, to the 5th.

This regenerates the heuristic function with the latest benchmark times, and removes the faiss block select in favour of kWarpImmediate and kRadix11bitsExtraPass.

### CODE REVIEW

**Review by tfeher — APPROVED** [review]
Thanks @benfred for the update, the PR looks good to me!

**Comment by achirkin** [comment]
@benfred Cool, just noticed this change! Does this close https://github.com/rapidsai/raft/issues/1975 ?  Also, is there anything still blocking us from removing the lefacy faiss neighbors::detail::select_k ?

**Comment by benfred** [comment]
@achirkin I think we can close out #1975 with this change - and I've also removed the legacy neibhors::detail::select_k code in #2027

**Pull request merged**
