### PR TITLE
use `matrix::select_k` in brute_force::knn call

### PR DESCRIPTION
**Pull request by benfred**

### CODE REVIEW

**Review by cjnolet — APPROVED** [review]

**Comment by benfred** [comment]
While times for small batches improves with this change, overall the performance seems to be quite a bit worse with this change - and this PR shouldn't be merged until after https://github.com/rapidsai/raft/pull/1455.

Running the neighbours benchmarks (modifying K from 32->128 to avoid hitting the fusedl2 path):

branch-23.06
```
KNN/float/int64_t/brute_force_knn/0/0/0/manual_time        75.2 ms          212 ms            9 2000000#128#1000#128#NO_COPY#BUILD_SEARCH
KNN/float/int64_t/brute_force_knn/0/1/0/manual_time        1992 ms         2091 ms            1 2000000#128#1000#128#MAP_PINNED#BUILD_SEARCH
KNN/float/int64_t/brute_force_knn/0/2/0/manual_time         273 ms         1260 ms            3 2000000#128#1000#128#MANAGED#BUILD_SEARCH
KNN/float/int64_t/brute_force_knn/1/0/0/manual_time         388 ms         1028 ms            2 10000000#128#1000#128#NO_COPY#BUILD_SEARCH
KNN/float/int64_t/brute_force_knn/1/1/0/manual_time        9959 ms        10425 ms            1 10000000#128#1000#128#MAP_PINNED#BUILD_SEARCH
KNN/float/int64_t/brute_force_knn/1/2/0/manual_time        1362 ms         6266 ms            1 10000000#128#1000#128#MANAGED#BUILD_SEARCH
KNN/float/int64_t/brute_force_knn/2/0/0/manual_time        14.0 ms         58.0 ms           50 10000#8192#1000#128#NO_COPY#BUILD_SEARCH
KNN/float/int64_t/brute_force_knn/2/1/0/manual_time         628 ms          663 ms            1 10000#8192#1000#128#MAP_PINNED#BUILD_SEARCH
KNN/float/int64_t/brute_force_knn/2/2/0/manual_time        47.6 ms          365 ms           15 10000#8192#1000#128#MANAGED#BUILD_SEARCH
KNN/float/uint32_t/brute_force_knn/0/0/0/manual_time       75.0 ms          213 ms            9 2000000#128#1000#128#NO_COPY#BUILD_SEARCH
KNN/float/uint32_t/brute_force_knn/0/1/0/manual_time       1991 ms         2090 ms            1 2000000#128#1000#128#MAP_PINNED#BUILD_SEARCH
KNN/float/uint32_t/brute_force_knn/0/2/0/manual_time        253 ms         1242 ms            2 2000000#128#1000#128#MANAGED#BUILD_SEARCH
KNN/float/uint32_t/brute_force_knn/1/0/0/manual_time        387 ms         1013 ms            2 10000000#128#1000#128#NO_COPY#BUILD_SEARCH
KNN/float/uint32_t/brute_force_knn/1/1/0/manual_time       9954 ms        10419 ms            1 10000000#128#1000#128#MAP_PINNED#BUILD_SEARCH
KNN/float/uint32_t/brute_force_knn/1/2/0/manual_time       1269 ms         6186 ms            1 10000000#128#1000#128#MANAGED#BUILD_SEARCH
KNN/float/uint32_t/brute_force_knn/2/0/0/manual_time       14.2 ms         58.6 ms           49 10000#8192#1000#128#NO_COPY#BUILD_SEARCH
KNN/float/uint32_t/brute_force_knn/2/1/0/manual_time        628 ms          663 ms            1 10000#8192#1000#128#MAP_PINNED#BUILD_SEARCH
KNN/float/uint32_t/brute_force_knn/2/2/0/manual_time       48.1 ms          366 ms           15 10000#8192#1000#128#MANAGED#BUILD_SEARCH
```

this branch:

```
-----------------------------------------------------------------------------------------------
Benchmark                                                     Time             CPU   Iterations
-----------------------------------------------------------------------------------------------
KNN/float/int64_t/brute_force_knn/0/0/0/manual_time         457 ms          587 ms            2 2000000#128#1000#128#NO_COPY#BUILD_SEARCH
KNN/float/int64_t/brute_force_knn/0/1/0/manual_time        2379 ms         2481 ms            1 2000000#128#1000#128#MAP_PINNED#BUILD_SEARCH
KNN/float/int64_t/brute_force_knn/0/2/0/manual_time         660 ms         1651 ms            1 2000000#128#1000#128#MANAGED#BUILD_SEARCH
KNN/float/int64_t/brute_force_knn/1/0/0/manual_time        2317 ms         2908 ms            1 10000000#128#1000#128#NO_COPY#BUILD_SEARCH
KNN/float/int64_t/brute_force_knn/1/1/0/manual_time       11917 ms        12391 ms            1 10000000#128#1000#128#MAP_PINNED#BUILD_SEARCH
KNN/float/int64_t/brute_force_knn/1/2/0/manual_time        3309 ms         8239 ms            1 10000000#128#1000#128#MANAGED#BUILD_SEARCH
KNN/float/int64_t/brute_force_knn/2/0/0/manual_time        14.1 ms         58.4 ms           50 10000#8192#1000#128#NO_COPY#BUILD_SEARCH
KNN/float/int64_t/brute_force_knn/2/1/0/manual_time         628 ms          663 ms            1 10000#8192#1000#128#MAP_PINNED#BUILD_SEARCH
KNN/float/int64_t/brute_force_knn/2/2/0/manual_time        48.2 ms          367 ms           14 10000#8192#1000#128#MANAGED#BUILD_SEARCH
KNN/float/uint32_t/brute_force_knn/0/0/0/manual_time       72.6 ms          212 ms           10 2000000#128#1000#128#NO_COPY#BUILD_SEARCH
KNN/float/uint32_t/brute_force_knn/0/1/0/manual_time       1990 ms         2092 ms            1 2000000#128#1000#128#MAP_PINNED#BUILD_SEARCH
KNN/float/uint32_t/brute_force_knn/0/2/0/manual_time        252 ms         1237 ms            3 2000000#128#1000#128#MANAGED#BUILD_SEARCH
KNN/float/uint32_t/brute_force_knn/1/0/0/manual_time        373 ms         1011 ms            2 10000000#128#1000#128#NO_COPY#BUILD_SEARCH
KNN/float/uint32_t/brute_force_knn/1/1/0/manual_time       9947 ms        10419 ms            1 10000000#128#1000#128#MAP_PINNED#BUILD_SEARCH
KNN/float/uint32_t/brute_force_knn/1/2/0/manual_time       1258 ms         6188 ms            1 10000000#128#1000#128#MANAGED#BUILD_SEARCH
KNN/float/uint32_t/brute_force_knn/2/0/0/manual_time       14.2 ms         58.6 ms           49 10000#8192#1000#128#NO_COPY#BUILD_SEARCH
KNN/float/uint32_t/brute_force_knn/2/1/0/manual_time        628 ms          665 ms            1 10000#8192#1000#128#MAP_PINNED#BUILD_SEARCH
KNN/float/uint32_t/brute_force_knn/2/2/0/manual_time       48.3 ms          367 ms           14 10000#8192#1000#128#MANAGED#BUILD_SEARCH
```

**Comment by benfred** [comment]
It does seem like the `matrix::select_k` code might have some performance issues with the int64_t IndexType - which isn't seen with the uint32_t IndexType.   As an example, looking at just a single benchmark:

23.06  (faiss block select)
```
KNN/float/int64_t/brute_force_knn/0/0/0/manual_time        75.2 ms          212 ms            9 2000000#128#1000#128#NO_COPY#BUILD_SEARCH
KNN/float/uint32_t/brute_force_knn/0/0/0/manual_time       75.0 ms          213 ms            9 2000000#128#1000#128#NO_COPY#BUILD_SEARCH
```

this branch (`matrix::select_k`:
```
KNN/float/int64_t/brute_force_knn/0/0/0/manual_time         457 ms          587 ms            2 2000000#128#1000#128#NO_COPY#BUILD_SEARCH
KNN/float/uint32_t/brute_force_knn/0/0/0/manual_time       72.6 ms          212 ms           10 2000000#128#1000#128#NO_COPY#BUILD_SEARCH
```

With the faiss block select code - there isn't much difference between using a int64_t or uint32_t IndexType, but with the matrix::select_k code there is.

**Comment by benfred** [comment]
Using the new select_k code from https://github.com/rapidsai/raft/pull/1523/ removes the perf regression we've been seeing with using `matrix::select_k` - and leads to a speedup in the bfknn code instead: 

```
-----------------------------------------------------------------------------------------------
Benchmark                                                     Time             CPU   Iterations
-----------------------------------------------------------------------------------------------
KNN/float/int64_t/brute_force_knn/0/0/0/manual_time        65.9 ms          177 ms           11 2000000#128#1000#128#NO_COPY#BUILD_SEARCH
KNN/float/int64_t/brute_force_knn/0/1/0/manual_time        1982 ms         2058 ms            1 2000000#128#1000#128#MAP_PINNED#BUILD_SEARCH
KNN/float/int64_t/brute_force_knn/0/2/0/manual_time         254 ms         1222 ms            3 2000000#128#1000#128#MANAGED#BUILD_SEARCH
KNN/float/int64_t/brute_force_knn/1/0/0/manual_time         340 ms          894 ms            2 10000000#128#1000#128#NO_COPY#BUILD_SEARCH
KNN/float/int64_t/brute_force_knn/1/1/0/manual_time        9905 ms        10266 ms            1 10000000#128#1000#128#MAP_PINNED#BUILD_SEARCH
KNN/float/int64_t/brute_force_knn/1/2/0/manual_time        1223 ms         6068 ms            1 10000000#128#1000#128#MANAGED#BUILD_SEARCH
KNN/float/int64_t/brute_force_knn/2/0/0/manual_time        13.8 ms         49.3 ms           51 10000#8192#1000#128#NO_COPY#BUILD_SEARCH
KNN/float/int64_t/brute_force_knn/2/1/0/manual_time         628 ms          652 ms            1 10000#8192#1000#128#MAP_PINNED#BUILD_SEARCH
KNN/float/int64_t/brute_force_knn/2/2/0/manual_time        57.3 ms          368 ms           12 10000#8192#1000#128#MANAGED#BUILD_SEARCH
KNN/float/uint32_t/brute_force_knn/0/0/0/manual_time       64.6 ms          176 ms           11 2000000#128#1000#128#NO_COPY#BUILD_SEARCH
KNN/float/uint32_t/brute_force_knn/0/1/0/manual_time       1981 ms         2057 ms            1 2000000#128#1000#128#MAP_PINNED#BUILD_SEARCH
KNN/float/uint32_t/brute_force_knn/0/2/0/manual_time        253 ms         1223 ms            3 2000000#128#1000#128#MANAGED#BUILD_SEARCH
KNN/float/uint32_t/brute_force_knn/1/0/0/manual_time        336 ms          892 ms            2 10000000#128#1000#128#NO_COPY#BUILD_SEARCH
KNN/float/uint32_t/brute_force_knn/1/1/0/manual_time       9903 ms        10264 ms            1 10000000#128#1000#128#MAP_PINNED#BUILD_SEARCH
KNN/float/uint32_t/brute_force_knn/1/2/0/manual_time       1221 ms         6066 ms            1 10000000#128#1000#128#MANAGED#BUILD_SEARCH
KNN/float/uint32_t/brute_force_knn/2/0/0/manual_time       13.9 ms         49.4 ms           50 10000#8192#1000#128#NO_COPY#BUILD_SEARCH
KNN/float/uint32_t/brute_force_knn/2/1/0/manual_time        628 ms          653 ms            1 10000#8192#1000#128#MAP_PINNED#BUILD_SEARCH
KNN/float/uint32_t/brute_force_knn/2/2/0/manual_time       57.7 ms          368 ms           12 10000#8192#1000#128#MANAGED#BUILD_SEARCH
```

Note: the speedup is even more pronounced with a smaller batch size (which isn't being benchmarked here).

**Review by cjnolet — APPROVED** [review]

**Pull request merged**
