### PR TITLE
Change CAGRA auto mode selection

### PR DESCRIPTION
**Pull request by enp1s0**
This PR changes the rule to select a CAGRA search mode as written in the [CAGRA paper](https://arxiv.org/abs/2308.15136).

### CODE REVIEW

**Review by tfeher — APPROVED** [review]
Thanks @enp1s0 for the PR, looks good to me!

**Comment by cjnolet** [comment]
@enp1s0 looks like there's a failure in the tests in CI [here](https://github.com/rapidsai/raft/actions/runs/6302350622/job/17110017713?pr=1830).

**Review by cjnolet — APPROVED** [review]

**Comment by enp1s0** [comment]
Thank you for merging the PR!

**Pull request merged**
