### PR TITLE
[REVIEW] Change `raft` docs theme to `pydata-sphinx-theme`

### PR DESCRIPTION
**Pull request by galipremsagar**
Similar to https://github.com/rapidsai/cuml/pull/4985, this PR changes the docs theme for `raft` to be in-line with rest of the rapids docs theme.

### CODE REVIEW

**Comment by cjnolet** [comment]
Hey @galipremsagar, I really like this theme overall. I think the top headings fit perfectly in place as well. 

I notice the `pylibraft` distance docs don't seem to be rendered the code example, at least for me, but that example is rendering fine in the nightlies.

**Comment by galipremsagar** [comment]
@cjnolet Is this the Distance API you are referring to?

Screen Shot 2022-11-17 at 2 24 13 PM



Attached is my local clean install build for html folder just incase : [raft_build.zip](https://github.com/rapidsai/raft/files/10035323/raft_build.zip)

**Comment by galipremsagar** [comment]
Ah, got it. I can see the issue. Working on it

**Comment by galipremsagar** [comment]
@cjnolet This should be fixed now:

Screen Shot 2022-11-17 at 3 57 43 PM

Build zip:  [raft_docs_build.zip](https://github.com/rapidsai/raft/files/10036025/raft_docs_build.zip)

**Review by ajschmidt8 — COMMENTED** [review]
is this PR intended to include changes to `build.sh`? From the PR title and description, I thought these changes would just be related to the docs theme

**Comment by galipremsagar** [comment]
> is this PR intended to include changes to `build.sh`? From the PR title and description, I thought these changes would just be related to the docs theme

So, when building locally we discovered `build.sh` needed changes for a successful local build. Hence packed the changes into this PR.

**Review by ajschmidt8 — APPROVED** [review]

**Comment by cjnolet** [comment]
@gpucibot merge

**Comment by cjnolet** [comment]
Arg, I hate weird failures. I just realized the conda recipe build scripts need to be updated (they were using the --install flag)

**Comment by galipremsagar** [comment]
> Arg, I hate weird failures. I just realized the conda recipe build scripts need to be updated (they were using the --install flag)

It should now be fixed, Apologies for the oversight

**Comment by cjnolet** [comment]
@gpucibot merge

**Pull request merged**
