### PR TITLE
ANN tests: make the min_recall check strict

### PR DESCRIPTION
**Pull request by achirkin**
In #1135, we adjusted the min_recall values to report if any regressions happen in ivf-pq. However, `eval_neighbours` function, which is used in several ANN test suites, doesn't fail unless the regression is really large (it prints a warning if the calculated recall is "slightly" smaller than the expected recall).
In this PR, I make `eval_neighbours` always fail if the calculated recall is smaller than the expected recall. Slightly adjust the tests and do a small refactoring along the way.

### CODE REVIEW

**Comment by achirkin** [comment]
NB: some of the affected algorithm are not deterministic due to concurrency etc.; I've successfully run the test suite on my workstation 35 times, but we should keep an eye on how it behaves on the CI machines as well.

**Comment by cjnolet** [comment]
My recent merge commit broke the build. Just leaving a note here that I'll fix this.

**Comment by achirkin** [comment]
Did a dozen tests on a100 and v100, seems to be passing with the latest adjustments.

**Pull request merged**
