### PR TITLE
 [ENH] [2/5] Header structure: remove specialization includes

### PR DESCRIPTION
**Pull request by ahendriksen**
Specializations are deprecated in PR #1437 . This PR removes includes of these deprecated headers.

On top of PR #1437, it adds a single commit:
- [d5b5673](https://github.com/rapidsai/raft/pull/1438/commits/d5b567397ca30c9e1f38e170adc52450626d97c5): Remove includes of specialization headers within RAFT.

### CODE REVIEW

**Comment by ahendriksen** [comment]
Review tip: the only difference compared to PR #1437 is the last commit. The full diff wrt branch-23.06 includes PR #1437, so it is a bit much.

**Review by tfeher — APPROVED** [review]
Reviwed the last commit, looks good to me.

**Review by divyegala — APPROVED** [review]
I love this one

**Review by cjnolet — APPROVED** [review]
LGTM, pending changes in #1437

**Pull request closed without merging**
