### PR TITLE
Testing conda compilers

### PR DESCRIPTION
**Pull request by cjnolet**

### CODE REVIEW

**Comment by cjnolet** [comment]
rerun tests

**Comment by cjnolet** [comment]
rerun tests

**Comment by cjnolet** [comment]
rerun tests

**Review by msadang — APPROVED** [review]
LGTM

**Review by dantegd — APPROVED** [review]

**Comment by cjnolet** [comment]
@gpucibot merge

**Comment by jakirkham** [comment]
Thanks Corey! 🙏

**Pull request merged**
