### PR TITLE
Try using contiguous rank to fix cuda_visible_devices

### PR DESCRIPTION
**Pull request by VibhuJawa**
This PR attempts to solve https://github.com/rapidsai/cugraph/issues/3889

### CODE REVIEW

**Comment by VibhuJawa** [comment]
Can confirm that with this [PR](https://github.com/rapidsai/cugraph/issues/3889) below issue is resolved . 
```
In [1]: from cugraph.testing.mg_utils import start_dask_client
In [2]: client, cluster = start_dask_client(dask_worker_devices=[1], jit_unspill=False)
```

**Comment by jnke2016** [comment]
Thanks @VibhuJawa.
This PR looks good to me. I will need to test this PR on Draco to make sure it doesn't bring back the `nccl` transient issue that was resolved few months ago

**Comment by VibhuJawa** [comment]
```ipython3
In [1]: from raft_dask.common import Comms
   ...: from dask_cuda import LocalCUDACluster
   ...: from dask.distributed import Client
   ...: 
   ...: cluster = LocalCUDACluster(CUDA_VISIBLE_DEVICES="1")
   ...: client = Client(cluster)
   ...: cb = Comms(verbose=True, comms_p2p=True)
   ...: cb.init()

```

With brach-23.12:
```
Initializing comms!
2023-10-24 18:44:17,633 - distributed.worker - WARNING - Run Failed
Function: _func_init_all
args:     (b'b\xbbF\xa8\x1d\xa6O0\xba\xd9\xcb\x16\xbd\xfe\xbd\xd4', b'\x9fW\x1bd\xfb\x81Rs\x02\x00\xcd\xab\n!\xe4F\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xe0\x11\x06VI\x7f\x00\x00 \xb6E\xa0E\x7f\x00\x00p\x86\xb4VI\x7f\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x02\x93\x86\xb1U\x00\x00\x00\x00\x00\x00\xce\x90\xd6*`^\xfa\x84\xb1U\x00\x00\xe0\x11\x06VI\x7f\x00\x00\x00\x03\xf6\x9a\x9c\xaa\xa3w \xb9U\xacE\x7f\x00\x00p\x86\xb4VI\x7f\x00', True, {'tcp://127.0.0.1:38629': {'rank': 1, 'port': 47810}}, True, 0)
kwargs:   {'dask_worker': <Worker 'tcp://127.0.0.1:38629', name: 1, status: running, stored: 0, running: 0/1, ready: 0, comm: 0, waiting: 0>}
Traceback (most recent call last):
  File "/datasets/vjawa/miniconda3/envs/cugraph_dev/lib/python3.10/site-packages/distributed/worker.py", line 3174, in run
    result = await function(*args, **kwargs)
  File "/datasets/vjawa/miniconda3/envs/cugraph_dev/lib/python3.10/site-packages/raft_dask/common/comms.py", line 446, in _func_init_all
    _func_init_nccl(sessionId, uniqueId, dask_worker=dask_worker)
  File "/datasets/vjawa/miniconda3/envs/cugraph_dev/lib/python3.10/site-packages/raft_dask/common/comms.py", line 511, in _func_init_nccl
    n.init(nWorkers, uniqueId, wid)
  File "nccl.pyx", line 151, in raft_dask.common.nccl.nccl.init
RuntimeError: NCCL_ERROR: b'invalid argument (run with NCCL_DEBUG=WARN for details)'
```

</details>

With PR:
```
Initializing comms!
Initialization complete.

```

**Review by cjnolet — APPROVED** [review]

**Review by cjnolet — APPROVED** [review]

**Pull request merged**
