### PR TITLE
Test updates of CCCL (thrust, cub, libcudacxx) to 2.1.0.

### PR DESCRIPTION
**Pull request by bdice**
This PR tests a rapids-cmake branch with CCCL (thrust, cub, libcudacxx) updated to 2.1.0. **Do not merge this PR.** The changes will be merged upstream in rapids-cmake after all libraries pass CI.

### CODE REVIEW

**Comment by cjnolet** [comment]
@bdice just checking in as I'm taking an inventory of open PRs for the 23.06 release. Is this PR still needed?

**Comment by bdice** [comment]
Also responded offline -- tl;dr yes, we will need to work on this but I'm trying to fix up cudf's PR before making recommendations on how to address the device lambda issues for raft and other libraries.

**Comment by bdice** [comment]
cudf's CCCL update PR is fully working so I'm starting work on RAFT now. I'm planning to work on the build/CMake/conda/etc. side and get to a point where C++ is building with the right versions. Once we see C++ failures (if any), I would like to pass this off to a RAFT dev so that I can continue setting up CCCL update PRs for other RAPIDS libraries. I can help identify the kinds of changes that might be needed -- let's see what fails and then I can advise accordingly. cc: @cjnolet

**Comment by bdice** [comment]
CUDA 12 builds were failing with:
```
/opt/conda/conda-bld/_build_env/targets/x86_64-linux/include/crt/host_defines.h:86: error: "__forceinline__" redefined [-Werror]
...
/opt/conda/conda-bld/work/cpp/build/_deps/libcudacxx-src/lib/cmake/libcudacxx/../../../include/cuda/std/detail/__config:39: note: this is the location of the previous definition
```

Full error output:
<details>

```
FAILED: CMakeFiles/CORE_TEST.dir/test/core/sparse_matrix.cpp.o 
sccache /opt/conda/conda-bld/_build_env/bin/x86_64-conda-linux-gnu-c++ -DCUTLASS_NAMESPACE=raft_cutlass -DFMT_HEADER_ONLY=1 -DRAFT_COMPILED -DRAFT_EXPLICIT_INSTANTIATE_ONLY -DRAFT_SYSTEM_LITTLE_ENDIAN=1 -DSPDLOG_FMT_EXTERNAL -DTHRUST_DEVICE_SYSTEM=THRUST_DEVICE_SYSTEM_CUDA -DTHRUST_HOST_SYSTEM=THRUST_HOST_SYSTEM_CPP -I/opt/conda/conda-bld/work/cpp/test -I/opt/conda/conda-bld/work/cpp/include -I/opt/conda/conda-bld/work/cpp/build/_deps/thrust-src/thrust/cmake/../.. -I/opt/conda/conda-bld/work/cpp/build/_deps/libcudacxx-src/lib/cmake/libcudacxx/../../../include -I/opt/conda/conda-bld/work/cpp/build/_deps/thrust-src/dependencies/cub/cub/cmake/../.. -I/opt/conda/conda-bld/work/cpp/build/_deps/nvidiacutlass-src/include -I/opt/conda/conda-bld/work/cpp/build/_deps/nvidiacutlass-build/include -I/opt/conda/conda-bld/_build_env/include -I/opt/conda/conda-bld/work/cpp/internal -isystem /opt/conda/include -fvisibility-inlines-hidden -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /opt/conda/conda-bld/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/include -fdebug-prefix-map=/opt/conda/conda-bld/work=/usr/local/src/conda/libraft-headers-only-23.10.00a -fdebug-prefix-map=/opt/conda/conda-bld/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho=/usr/local/src/conda-prefix  -I/opt/conda/conda-bld/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/targets/x86_64-linux/include -I/opt/conda/conda-bld/_build_env/targets/x86_64-linux/include  -L/opt/conda/conda-bld/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/targets/x86_64-linux/lib -L/opt/conda/conda-bld/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/targets/x86_64-linux/lib/stubs -L/opt/conda/conda-bld/_build_env/targets/x86_64-linux/lib -L/opt/conda/conda-bld/_build_env/targets/x86_64-linux/lib/stubs -O3 -DNDEBUG -std=gnu++17 -fPIE -Wno-deprecated-declarations -Wall -Werror -Wno-unknown-pragmas -Wno-error=deprecated-declarations -DCUDA_API_PER_THREAD_DEFAULT_STREAM -pthread -fopenmp -MD -MT CMakeFiles/CORE_TEST.dir/test/core/sparse_matrix.cpp.o -MF CMakeFiles/CORE_TEST.dir/test/core/sparse_matrix.cpp.o.d -o CMakeFiles/CORE_TEST.dir/test/core/sparse_matrix.cpp.o -c /opt/conda/conda-bld/work/cpp/test/core/sparse_matrix.cpp
In file included from /opt/conda/conda-bld/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/targets/x86_64-linux/include/cuda_runtime_api.h:147,
                 from /opt/conda/conda-bld/work/cpp/build/_deps/thrust-src/dependencies/cub/cub/cmake/../../cub/detail/detect_cuda_runtime.cuh:38,
                 from /opt/conda/conda-bld/work/cpp/build/_deps/thrust-src/dependencies/cub/cub/cmake/../../cub/util_arch.cuh:41,
                 from /opt/conda/conda-bld/work/cpp/build/_deps/thrust-src/dependencies/cub/cub/cmake/../../cub/util_debug.cuh:40,
                 from /opt/conda/conda-bld/work/cpp/build/_deps/thrust-src/thrust/cmake/../../thrust/system/cuda/config.h:43,
                 from /opt/conda/conda-bld/work/cpp/build/_deps/thrust-src/thrust/cmake/../../thrust/system/cuda/detail/execution_policy.h:35,
                 from /opt/conda/conda-bld/work/cpp/build/_deps/thrust-src/thrust/cmake/../../thrust/iterator/detail/device_system_tag.h:23,
                 from /opt/conda/conda-bld/work/cpp/build/_deps/thrust-src/thrust/cmake/../../thrust/iterator/iterator_traits.h:62,
                 from /opt/conda/conda-bld/work/cpp/build/_deps/thrust-src/thrust/cmake/../../thrust/distance.h:25,
                 from /opt/conda/conda-bld/work/cpp/include/raft/core/span.hpp:28,
                 from /opt/conda/conda-bld/work/cpp/include/raft/core/coo_matrix.hpp:21,
                 from /opt/conda/conda-bld/work/cpp/include/raft/core/host_coo_matrix.hpp:18,
                 from /opt/conda/conda-bld/work/cpp/test/core/sparse_matrix.cpp:17:
/opt/conda/conda-bld/_build_env/targets/x86_64-linux/include/crt/host_defines.h:86: error: "__forceinline__" redefined [-Werror]
   86 | #define __forceinline__ \
      | 
In file included from /opt/conda/conda-bld/work/cpp/build/_deps/libcudacxx-src/lib/cmake/libcudacxx/../../../include/cuda/std/utility:14,
                 from /opt/conda/conda-bld/work/cpp/build/_deps/thrust-src/dependencies/cub/cub/cmake/../../cub/util_macro.cuh:35,
                 from /opt/conda/conda-bld/work/cpp/build/_deps/thrust-src/dependencies/cub/cub/cmake/../../cub/util_arch.cuh:38,
                 from /opt/conda/conda-bld/work/cpp/build/_deps/thrust-src/dependencies/cub/cub/cmake/../../cub/util_debug.cuh:40,
                 from /opt/conda/conda-bld/work/cpp/build/_deps/thrust-src/thrust/cmake/../../thrust/system/cuda/config.h:43,
                 from /opt/conda/conda-bld/work/cpp/build/_deps/thrust-src/thrust/cmake/../../thrust/system/cuda/detail/execution_policy.h:35,
                 from /opt/conda/conda-bld/work/cpp/build/_deps/thrust-src/thrust/cmake/../../thrust/iterator/detail/device_system_tag.h:23,
                 from /opt/conda/conda-bld/work/cpp/build/_deps/thrust-src/thrust/cmake/../../thrust/iterator/iterator_traits.h:62,
                 from /opt/conda/conda-bld/work/cpp/build/_deps/thrust-src/thrust/cmake/../../thrust/distance.h:25,
                 from /opt/conda/conda-bld/work/cpp/include/raft/core/span.hpp:28,
                 from /opt/conda/conda-bld/work/cpp/include/raft/core/coo_matrix.hpp:21,
                 from /opt/conda/conda-bld/work/cpp/include/raft/core/host_coo_matrix.hpp:18,
                 from /opt/conda/conda-bld/work/cpp/test/core/sparse_matrix.cpp:17:
/opt/conda/conda-bld/work/cpp/build/_deps/libcudacxx-src/lib/cmake/libcudacxx/../../../include/cuda/std/detail/__config:39: note: this is the location of the previous definition
   39 |         #define __forceinline__
      | 
cc1plus: all warnings being treated as errors
```

</details>

This is the same issue that was fixed in https://github.com/NVIDIA/libcudacxx/pull/476, but that hasn't been released yet in CCCL 2.1.0. I tried to add a patch upstream in rapids-cmake for this issue in libcudacxx 2.1.0, but it's a pretty big patch (+866 / -888 lines) and didn't apply cleanly, so it might take a lot of manual reworking. We might be better served by going straight to CCCL 2.2.0 where this fix will land but that will require waiting for the 2.2.0 tag (coming soon?) as well as adopting changes in rapids-cmake to support the monorepo.

For now, I have added `#include <cuda_runtime.h>` to the affected files with a note describing the workaround and solution (remove when adopting CCCL 2.2.0).

**Comment by bdice** [comment]
Closing in favor of #2049.

**Pull request closed without merging**
