### PR TITLE
Relax UCX pin to allow 1.14

### PR DESCRIPTION
**Pull request by pentschev**
UCX 1.14.0 was recently released and conda-forge package was updated in https://github.com/conda-forge/ucx-split-feedstock/pull/111 with several packaging improvements. Relax the pin to allow installing UCX v1.14.x as well.

### CODE REVIEW

**Review by ajschmidt8 — APPROVED** [review]

**Comment by ajschmidt8** [comment]
@pentschev, pushed a small fix for a syntax error that resulted from these changes.

please double-check it. thanks!

**Comment by pentschev** [comment]
Looks good, thanks @ajschmidt8 for catching that!

**Comment by jakirkham** [comment]
Looks like CI is passing

**Pull request merged**
