### PR TITLE
Add column major input support in contractions_nt kernels with new kernel policy for it

### PR DESCRIPTION
**Pull request by mdoijade**

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by mdoijade** [comment]
@teju85 for help with review.

**Review by teju85 — APPROVED** [review]
Changes LGTM.

**Comment by mdoijade** [comment]
@divyegala please help with review.

**Review by divyegala — APPROVED** [review]
LGTM because @teju85 has approved it. We are working on getting my review being required with ops for merging to work

**Comment by teju85** [comment]
Thank you Divye! I guess since this is Mahesh's first PR to raft, this requires a whitelisting from the admin team? @JohnZed ?

**Comment by cjnolet** [comment]
rerun tests

**Comment by JohnZed** [comment]
ok to test

**Comment by mdoijade** [comment]
@teju85 is this PR now good to merge? Who can merge it?

**Comment by teju85** [comment]
@gpucibot merge

**Pull request merged**
