### PR TITLE
Warnings are errors

### LINKED ISSUE #225: [BUG] Build RAFT tests with `-Wall -Werror`
As a header-only library, warnings in RAFT can cause errors in consuming libs that compile with `-Werror`. Building tests with `-Wall -Werror` [like RMM does](https://github.com/rapidsai/rmm/blob/7768d4d0faa3401e9dd455db47125370be63b983/tests/CMakeLists.txt#L56-L57) should catch most problems before they're released.

For example, see this error in a RAFT header when compiling cuML:
```
raft/cpp/include/raft/sparse/hierarchy/detail/mst.cuh: In instantiation of 'void raft::hierarchy::detail::build_sorted_mst(const raft::handle_t&, const value_t*, const value_idx*, const value_idx*, const value_t*, size_t, size_t, rmm::device_uvector<value_idx>&, rmm::device_uvector<value_idx>&, rmm::device_uvector<value_t>&, size_t, raft::distance::DistanceType, int) [with value_idx = int; value_t = float; size_t = long unsigned int]':
raft/cpp/include/raft/sparse/hierarchy/single_linkage.hpp:80:47:   required from 'void raft::hierarchy::single_linkage(const raft::handle_t&, const value_t*, size_t, size_t, raft::distance::DistanceType, raft::hierarchy::linkage_output<value_idx, value_t>*, int, size_t) [with value_idx = int; value_t = float; raft::hierarchy::LinkageDistance dist_type = raft::hierarchy::PAIRWISE; size_t = long unsigned int]'
cuml/cpp/src/hierarchy/linkage.cu:32:117:   required from here
raft/cpp/include/raft/sparse/hierarchy/detail/mst.cuh:204:410: warning: format '%d' expects argument of type 'int', but argument 4 has type 'size_t' {aka 'long unsigned int'} [-Wformat=]
```

### LINKED ISSUE #289: [BUG] Update cuSparse deprecated calls
**Describe the bug**
Compiling with raft produces the following many wanrings.

```
In file included from /raid/seunghwak/RAPIDS/development/cugraph/cpp/build/_deps/raft-src/cpp/include/raft/handle.hpp:37,
                 from /raid/seunghwak/RAPIDS/development/cugraph/cpp/tests/utilities/device_comm_wrapper.hpp:19,
                 from /raid/seunghwak/RAPIDS/development/cugraph/cpp/tests/experimental/mg_sssp_test.cpp:19:
/raid/seunghwak/RAPIDS/development/cugraph/cpp/build/_deps/raft-src/cpp/include/raft/sparse/cusparse_wrappers.h: In function ‘cusparseStatus_t raft::sparse::cusparsecsrmvex_bufferSize(cusparseHandle_t, cusparseAlgMode_t, cusparseOperation_t, int, int, int, const T*, cusparseMatDescr_t, const T*, const int*, const int*, const T*, const T*, T*, size_t*, cudaStream_t) [with T = float; cusparseHandle_t = cusparseContext*; cusparseMatDescr_t = cusparseMatDescr*; size_t = long unsigned int; cudaStream_t = CUstream_st*]’:
/raid/seunghwak/RAPIDS/development/cugraph/cpp/build/_deps/raft-src/cpp/include/raft/sparse/cusparse_wrappers.h:583:46: warning: ‘cusparseStatus_t cusparseCsrmvEx_bufferSize(cusparseHandle_t, cusparseAlgMode_t, cusparseOperation_t, int, int, int, const void*, cudaDataType, cusparseMatDescr_t, const void*, cudaDataType, const int*, const int*, const void*, cudaDataType, const void*, cudaDataType, void*, cudaDataType, cudaDataType, size_t*)’ is deprecated: please use cusparseSpMV instead [-Wdeprecated-declarations]
  583 |     CUDA_R_32F, CUDA_R_32F, bufferSizeInBytes);
      |                                              ^
In file included from /usr/local/cuda/include/cusolverSp.h:53,
                 from /raid/seunghwak/RAPIDS/development/cugraph/cpp/build/_deps/raft-src/cpp/include/raft/handle.hpp:29,
                 from /raid/seunghwak/RAPIDS/development/cugraph/cpp/tests/utilities/device_comm_wrapper.hpp:19,
                 from /raid/seunghwak/RAPIDS/development/cugraph/cpp/tests/experimental/mg_sssp_test.cpp:19:
/usr/local/cuda/include/cusparse.h:710:1: note: declared here
  710 | cusparseCsrmvEx_bufferSize(cusparseHandle_t         handle,
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /raid/seunghwak/RAPIDS/development/cugraph/cpp/build/_deps/raft-src/cpp/include/raft/handle.hpp:37,
                 from /raid/seunghwak/RAPIDS/development/cugraph/cpp/tests/utilities/device_comm_wrapper.hpp:19,
                 from /raid/seunghwak/RAPIDS/development/cugraph/cpp/tests/experimental/mg_sssp_test.cpp:19:
/raid/seunghwak/RAPIDS/development/cugraph/cpp/build/_deps/raft-src/cpp/include/raft/sparse/cusparse_wrappers.h:583:46: warning: ‘cusparseStatus_t cusparseCsrmvEx_bufferSize(cusparseHandle_t, cusparseAlgMode_t, cusparseOperation_t, int, int, int, const void*, cudaDataType, cusparseMatDescr_t, const void*, cudaDataType, const int*, const int*, const void*, cudaDataType, const void*, cudaDataType, void*, cudaDataType, cudaDataType, size_t*)’ is deprecated: please use cusparseSpMV instead [-Wdeprecated-declarations]
  583 |     CUDA_R_32F, CUDA_R_32F, bufferSizeInBytes);
      |                                              ^
In file included from /usr/local/cuda/include/cusolverSp.h:53,
                 from /raid/seunghwak/RAPIDS/development/cugraph/cpp/build/_deps/raft-src/cpp/include/raft/handle.hpp:29,
                 from /raid/seunghwak/RAPIDS/development/cugraph/cpp/tests/utilities/device_comm_wrapper.hpp:19,
                 from /raid/seunghwak/RAPIDS/development/cugraph/cpp/tests/experimental/mg_sssp_test.cpp:19:
/usr/local/cuda/include/cusparse.h:710:1: note: declared here
  710 | cusparseCsrmvEx_bufferSize(cusparseHandle_t         handle,
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /raid/seunghwak/RAPIDS/development/cugraph/cpp/build/_deps/raft-src/cpp/include/raft/handle.hpp:37,
                 from /raid/seunghwak/RAPIDS/development/cugraph/cpp/tests/utilities/device_comm_wrapper.hpp:19,
                 from /raid/seunghwak/RAPIDS/development/cugraph/cpp/tests/experimental/mg_sssp_test.cpp:19:
/raid/seunghwak/RAPIDS/development/cugraph/cpp/build/_deps/raft-src/cpp/include/raft/sparse/cusparse_wrappers.h: In function ‘cusparseStatus_t raft::sparse::cusparsecsrmvex_bufferSize(cusparseHandle_t, cusparseAlgMode_t, cusparseOperation_t, int, int, int, const T*, cusparseMatDescr_t, const T*, const int*, const int*, const T*, const T*, T*, size_t*, cudaStream_t) [with T = double; cusparseHandle_t = cusparseContext*; cusparseMatDescr_t = cusparseMatDescr*; size_t = long unsigned int; cudaStream_t = CUstream_st*]’:
/raid/seunghwak/RAPIDS/development/cugraph/cpp/build/_deps/raft-src/cpp/include/raft/sparse/cusparse_wrappers.h:596:46: warning: ‘cusparseStatus_t cusparseCsrmvEx_bufferSize(cusparseHandle_t, cusparseAlgMode_t, cusparseOperation_t, int, int, int, const void*, cudaDataType, cusparseMatDescr_t, const void*, cudaDataType, const int*, const int*, const void*, cudaDataType, const void*, cudaDataType, void*, cudaDataType, cudaDataType, size_t*)’ is deprecated: please use cusparseSpMV instead [-Wdeprecated-declarations]
  596 |     CUDA_R_64F, CUDA_R_64F, bufferSizeInBytes);
      |                                              ^
In file included from /usr/local/cuda/include/cusolverSp.h:53,
                 from /raid/seunghwak/RAPIDS/development/cugraph/cpp/build/_deps/raft-src/cpp/include/raft/handle.hpp:29,
                 from /raid/seunghwak/RAPIDS/development/cugraph/cpp/tests/utilities/device_comm_wrapper.hpp:19,
                 from /raid/seunghwak/RAPIDS/development/cugraph/cpp/tests/experimental/mg_sssp_test.cpp:19:
/usr/local/cuda/include/cusparse.h:710:1: note: declared here
  710 | cusparseCsrmvEx_bufferSize(cusparseHandle_t         handle,
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /raid/seunghwak/RAPIDS/development/cugraph/cpp/build/_deps/raft-src/cpp/include/raft/handle.hpp:37,
                 from /raid/seunghwak/RAPIDS/development/cugraph/cpp/tests/utilities/device_comm_wrapper.hpp:19,
                 from /raid/seunghwak/RAPIDS/development/cugraph/cpp/tests/experimental/mg_sssp_test.cpp:19:
/raid/seunghwak/RAPIDS/development/cugraph/cpp/build/_deps/raft-src/cpp/include/raft/sparse/cusparse_wrappers.h:596:46: warning: ‘cusparseStatus_t cusparseCsrmvEx_bufferSize(cusparseHandle_t, cusparseAlgMode_t, cusparseOperation_t, int, int, int, const void*, cudaDataType, cusparseMatDescr_t, const void*, cudaDataType, const int*, const int*, const void*, cudaDataType, const void*, cudaDataType, void*, cudaDataType, cudaDataType, size_t*)’ is deprecated: please use cusparseSpMV instead [-Wdeprecated-declarations]
  596 |     CUDA_R_64F, CUDA_R_64F, bufferSizeInBytes);
      |                                              ^
In file included from /usr/local/cuda/include/cusolverSp.h:53,
                 from /raid/seunghwak/RAPIDS/development/cugraph/cpp/build/_deps/raft-src/cpp/include/raft/handle.hpp:29,
                 from /raid/seunghwak/RAPIDS/development/cugraph/cpp/tests/utilities/device_comm_wrapper.hpp:19,
                 from /raid/seunghwak/RAPIDS/development/cugraph/cpp/tests/experimental/mg_sssp_test.cpp:19:
/usr/local/cuda/include/cusparse.h:710:1: note: declared here
  710 | cusparseCsrmvEx_bufferSize(cusparseHandle_t         handle,
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /raid/seunghwak/RAPIDS/development/cugraph/cpp/build/_deps/raft-src/cpp/include/raft/handle.hpp:37,
                 from /raid/seunghwak/RAPIDS/development/cugraph/cpp/tests/utilities/device_comm_wrapper.hpp:19,
                 from /raid/seunghwak/RAPIDS/development/cugraph/cpp/tests/experimental/mg_sssp_test.cpp:19:
/raid/seunghwak/RAPIDS/development/cugraph/cpp/build/_deps/raft-src/cpp/include/raft/sparse/cusparse_wrappers.h: In function ‘cusparseStatus_t raft::sparse::cusparsecsrmvex(cusparseHandle_t, cusparseAlgMode_t, cusparseOperation_t, int, int, int, const T*, cusparseMatDescr_t, const T*, const int*, const int*, const T*, const T*, T*, T*, cudaStream_t) [with T = float; cusparseHandle_t = cusparseContext*; cusparseMatDescr_t = cusparseMatDescr*; cudaStream_t = CUstream_st*]’:
/raid/seunghwak/RAPIDS/development/cugraph/cpp/build/_deps/raft-src/cpp/include/raft/sparse/cusparse_wrappers.h:616:44: warning: ‘cusparseStatus_t cusparseCsrmvEx(cusparseHandle_t, cusparseAlgMode_t, cusparseOperation_t, int, int, int, const void*, cudaDataType, cusparseMatDescr_t, const void*, cudaDataType, const int*, const int*, const void*, cudaDataType, const void*, cudaDataType, void*, cudaDataType, cudaDataType, void*)’ is deprecated: please use cusparseSpMV instead [-Wdeprecated-declarations]
  616 |                          CUDA_R_32F, buffer);
      |                                            ^
In file included from /usr/local/cuda/include/cusolverSp.h:53,
                 from /raid/seunghwak/RAPIDS/development/cugraph/cpp/build/_deps/raft-src/cpp/include/raft/handle.hpp:29,
                 from /raid/seunghwak/RAPIDS/development/cugraph/cpp/tests/utilities/device_comm_wrapper.hpp:19,
                 from /raid/seunghwak/RAPIDS/development/cugraph/cpp/tests/experimental/mg_sssp_test.cpp:19:
/usr/local/cuda/include/cusparse.h:734:1: note: declared here
  734 | cusparseCsrmvEx(cusparseHandle_t         handle,
      | ^~~~~~~~~~~~~~~
In file included from /raid/seunghwak/RAPIDS/development/cugraph/cpp/build/_deps/raft-src/cpp/include/raft/handle.hpp:37,
                 from /raid/seunghwak/RAPIDS/development/cugraph/cpp/tests/utilities/device_comm_wrapper.hpp:19,
                 from /raid/seunghwak/RAPIDS/development/cugraph/cpp/tests/experimental/mg_sssp_test.cpp:19:
/raid/seunghwak/RAPIDS/development/cugraph/cpp/build/_deps/raft-src/cpp/include/raft/sparse/cusparse_wrappers.h:616:44: warning: ‘cusparseStatus_t cusparseCsrmvEx(cusparseHandle_t, cusparseAlgMode_t, cusparseOperation_t, int, int, int, const void*, cudaDataType, cusparseMatDescr_t, const void*, cudaDataType, const int*, const int*, const void*, cudaDataType, const void*, cudaDataType, void*, cudaDataType, cudaDataType, void*)’ is deprecated: please use cusparseSpMV instead [-Wdeprecated-declarations]
  616 |                          CUDA_R_32F, buffer);
      |                                            ^
In file included from /usr/local/cuda/include/cusolverSp.h:53,
                 from /raid/seunghwak/RAPIDS/development/cugraph/cpp/build/_deps/raft-src/cpp/include/raft/handle.hpp:29,
                 from /raid/seunghwak/RAPIDS/development/cugraph/cpp/tests/utilities/device_comm_wrapper.hpp:19,
                 from /raid/seunghwak/RAPIDS/development/cugraph/cpp/tests/experimental/mg_sssp_test.cpp:19:
/usr/local/cuda/include/cusparse.h:734:1: note: declared here
  734 | cusparseCsrmvEx(cusparseHandle_t         handle,
      | ^~~~~~~~~~~~~~~
In file included from /raid/seunghwak/RAPIDS/development/cugraph/cpp/build/_deps/raft-src/cpp/include/raft/handle.hpp:37,
                 from /raid/seunghwak/RAPIDS/development/cugraph/cpp/tests/utilities/device_comm_wrapper.hpp:19,
                 from /raid/seunghwak/RAPIDS/development/cugraph/cpp/tests/experimental/mg_sssp_test.cpp:19:
/raid/seunghwak/RAPIDS/development/cugraph/cpp/build/_deps/raft-src/cpp/include/raft/sparse/cusparse_wrappers.h: In function ‘cusparseStatus_t raft::sparse::cusparsecsrmvex(cusparseHandle_t, cusparseAlgMode_t, cusparseOperation_t, int, int, int, const T*, cusparseMatDescr_t, const T*, const int*, const int*, const T*, const T*, T*, T*, cudaStream_t) [with T = double; cusparseHandle_t = cusparseContext*; cusparseMatDescr_t = cusparseMatDescr*; cudaStream_t = CUstream_st*]’:
/raid/seunghwak/RAPIDS/development/cugraph/cpp/build/_deps/raft-src/cpp/include/raft/sparse/cusparse_wrappers.h:629:44: warning: ‘cusparseStatus_t cusparseCsrmvEx(cusparseHandle_t, cusparseAlgMode_t, cusparseOperation_t, int, int, int, const void*, cudaDataType, cusparseMatDescr_t, const void*, cudaDataType, const int*, const int*, const void*, cudaDataType, const void*, cudaDataType, void*, cudaDataType, cudaDataType, void*)’ is deprecated: please use cusparseSpMV instead [-Wdeprecated-declarations]
  629 |                          CUDA_R_64F, buffer);
      |                                            ^
In file included from /usr/local/cuda/include/cusolverSp.h:53,
                 from /raid/seunghwak/RAPIDS/development/cugraph/cpp/build/_deps/raft-src/cpp/include/raft/handle.hpp:29,
                 from /raid/seunghwak/RAPIDS/development/cugraph/cpp/tests/utilities/device_comm_wrapper.hpp:19,
                 from /raid/seunghwak/RAPIDS/development/cugraph/cpp/tests/experimental/mg_sssp_test.cpp:19:
/usr/local/cuda/include/cusparse.h:734:1: note: declared here
  734 | cusparseCsrmvEx(cusparseHandle_t         handle,
      | ^~~~~~~~~~~~~~~
In file included from /raid/seunghwak/RAPIDS/development/cugraph/cpp/build/_deps/raft-src/cpp/include/raft/handle.hpp:37,
                 from /raid/seunghwak/RAPIDS/development/cugraph/cpp/tests/utilities/device_comm_wrapper.hpp:19,
                 from /raid/seunghwak/RAPIDS/development/cugraph/cpp/tests/experimental/mg_sssp_test.cpp:19:
/raid/seunghwak/RAPIDS/development/cugraph/cpp/build/_deps/raft-src/cpp/include/raft/sparse/cusparse_wrappers.h:629:44: warning: ‘cusparseStatus_t cusparseCsrmvEx(cusparseHandle_t, cusparseAlgMode_t, cusparseOperation_t, int, int, int, const void*, cudaDataType, cusparseMatDescr_t, const void*, cudaDataType, const int*, const int*, const void*, cudaDataType, const void*, cudaDataType, void*, cudaDataType, cudaDataType, void*)’ is deprecated: please use cusparseSpMV instead [-Wdeprecated-declarations]
  629 |                          CUDA_R_64F, buffer);
      |                                            ^
In file included from /usr/local/cuda/include/cusolverSp.h:53,
                 from /raid/seunghwak/RAPIDS/development/cugraph/cpp/build/_deps/raft-src/cpp/include/raft/handle.hpp:29,
                 from /raid/seunghwak/RAPIDS/development/cugraph/cpp/tests/utilities/device_comm_wrapper.hpp:19,
                 from /raid/seunghwak/RAPIDS/development/cugraph/cpp/tests/experimental/mg_sssp_test.cpp:19:
/usr/local/cuda/include/cusparse.h:734:1: note: declared here
  734 | cusparseCsrmvEx(cusparseHandle_t         handle,
      | ^~~~~~~~~~~~~~~
In file included from /raid/seunghwak/RAPIDS/development/cugraph/cpp/build/_deps/raft-src/cpp/include/raft/handle.hpp:37,
                 from /raid/seunghwak/RAPIDS/development/cugraph/cpp/tests/utilities/device_comm_wrapper.hpp:19,
                 from /raid/seunghwak/RAPIDS/development/cugraph/cpp/tests/experimental/mg_sssp_test.cpp:19:
/raid/seunghwak/RAPIDS/development/cugraph/cpp/build/_deps/raft-src/cpp/include/raft/sparse/cusparse_wrappers.h: In function ‘cusparseStatus_t raft::sparse::cusparsecsr2dense(cusparseHandle_t, int, int, cusparseMatDescr_t, const T*, const int*, const int*, T*, int, cudaStream_t) [with T = float; cusparseHandle_t = cusparseContext*; cusparseMatDescr_t = cusparseMatDescr*; cudaStream_t = CUstream_st*]’:
/raid/seunghwak/RAPIDS/development/cugraph/cpp/build/_deps/raft-src/cpp/include/raft/sparse/cusparse_wrappers.h:852:47: warning: ‘cusparseStatus_t cusparseScsr2dense(cusparseHandle_t, int, int, cusparseMatDescr_t, const float*, const int*, const int*, float*, int)’ is deprecated: please use cusparseSparseToDense instead [-Wdeprecated-declarations]
  852 |                             csrColIndA, A, lda);
      |                                               ^
In file included from /usr/local/cuda/include/cusolverSp.h:53,
                 from /raid/seunghwak/RAPIDS/development/cugraph/cpp/build/_deps/raft-src/cpp/include/raft/handle.hpp:29,
                 from /raid/seunghwak/RAPIDS/development/cugraph/cpp/tests/utilities/device_comm_wrapper.hpp:19,
                 from /raid/seunghwak/RAPIDS/development/cugraph/cpp/tests/experimental/mg_sssp_test.cpp:19:
/usr/local/cuda/include/cusparse.h:4098:1: note: declared here
 4098 | cusparseScsr2dense(cusparseHandle_t         handle,
      | ^~~~~~~~~~~~~~~~~~
In file included from /raid/seunghwak/RAPIDS/development/cugraph/cpp/build/_deps/raft-src/cpp/include/raft/handle.hpp:37,
                 from /raid/seunghwak/RAPIDS/development/cugraph/cpp/tests/utilities/device_comm_wrapper.hpp:19,
                 from /raid/seunghwak/RAPIDS/development/cugraph/cpp/tests/experimental/mg_sssp_test.cpp:19:
/raid/seunghwak/RAPIDS/development/cugraph/cpp/build/_deps/raft-src/cpp/include/raft/sparse/cusparse_wrappers.h:852:47: warning: ‘cusparseStatus_t cusparseScsr2dense(cusparseHandle_t, int, int, cusparseMatDescr_t, const float*, const int*, const int*, float*, int)’ is deprecated: please use cusparseSparseToDense instead [-Wdeprecated-declarations]
  852 |                             csrColIndA, A, lda);
      |                                               ^
In file included from /usr/local/cuda/include/cusolverSp.h:53,
                 from /raid/seunghwak/RAPIDS/development/cugraph/cpp/build/_deps/raft-src/cpp/include/raft/handle.hpp:29,
                 from /raid/seunghwak/RAPIDS/development/cugraph/cpp/tests/utilities/device_comm_wrapper.hpp:19,
                 from /raid/seunghwak/RAPIDS/development/cugraph/cpp/tests/experimental/mg_sssp_test.cpp:19:
/usr/local/cuda/include/cusparse.h:4098:1: note: declared here
 4098 | cusparseScsr2dense(cusparseHandle_t         handle,
      | ^~~~~~~~~~~~~~~~~~
In file included from /raid/seunghwak/RAPIDS/development/cugraph/cpp/build/_deps/raft-src/cpp/include/raft/handle.hpp:37,
                 from /raid/seunghwak/RAPIDS/development/cugraph/cpp/tests/utilities/device_comm_wrapper.hpp:19,
                 from /raid/seunghwak/RAPIDS/development/cugraph/cpp/tests/experimental/mg_sssp_test.cpp:19:
/raid/seunghwak/RAPIDS/development/cugraph/cpp/build/_deps/raft-src/cpp/include/raft/sparse/cusparse_wrappers.h: In function ‘cusparseStatus_t raft::sparse::cusparsecsr2dense(cusparseHandle_t, int, int, cusparseMatDescr_t, const T*, const int*, const int*, T*, int, cudaStream_t) [with T = double; cusparseHandle_t = cusparseContext*; cusparseMatDescr_t = cusparseMatDescr*; cudaStream_t = CUstream_st*]’:
/raid/seunghwak/RAPIDS/development/cugraph/cpp/build/_deps/raft-src/cpp/include/raft/sparse/cusparse_wrappers.h:863:47: warning: ‘cusparseStatus_t cusparseDcsr2dense(cusparseHandle_t, int, int, cusparseMatDescr_t, const double*, const int*, const int*, double*, int)’ is deprecated: please use cusparseSparseToDense instead [-Wdeprecated-declarations]
  863 |                             csrColIndA, A, lda);
      |                                               ^
In file included from /usr/local/cuda/include/cusolverSp.h:53,
                 from /raid/seunghwak/RAPIDS/development/cugraph/cpp/build/_deps/raft-src/cpp/include/raft/handle.hpp:29,
                 from /raid/seunghwak/RAPIDS/development/cugraph/cpp/tests/utilities/device_comm_wrapper.hpp:19,
                 from /raid/seunghwak/RAPIDS/development/cugraph/cpp/tests/experimental/mg_sssp_test.cpp:19:
/usr/local/cuda/include/cusparse.h:4110:1: note: declared here
 4110 | cusparseDcsr2dense(cusparseHandle_t         handle,
      | ^~~~~~~~~~~~~~~~~~
In file included from /raid/seunghwak/RAPIDS/development/cugraph/cpp/build/_deps/raft-src/cpp/include/raft/handle.hpp:37,
                 from /raid/seunghwak/RAPIDS/development/cugraph/cpp/tests/utilities/device_comm_wrapper.hpp:19,
                 from /raid/seunghwak/RAPIDS/development/cugraph/cpp/tests/experimental/mg_sssp_test.cpp:19:
/raid/seunghwak/RAPIDS/development/cugraph/cpp/build/_deps/raft-src/cpp/include/raft/sparse/cusparse_wrappers.h:863:47: warning: ‘cusparseStatus_t cusparseDcsr2dense(cusparseHandle_t, int, int, cusparseMatDescr_t, const double*, const int*, const int*, double*, int)’ is deprecated: please use cusparseSparseToDense instead [-Wdeprecated-declarations]
  863 |                             csrColIndA, A, lda);
      |                                               ^
In file included from /usr/local/cuda/include/cusolverSp.h:53,
                 from /raid/seunghwak/RAPIDS/development/cugraph/cpp/build/_deps/raft-src/cpp/include/raft/handle.hpp:29,
                 from /raid/seunghwak/RAPIDS/development/cugraph/cpp/tests/utilities/device_comm_wrapper.hpp:19,
                 from /raid/seunghwak/RAPIDS/development/cugraph/cpp/tests/experimental/mg_sssp_test.cpp:19:
/usr/local/cuda/include/cusparse.h:4110:1: note: declared here
 4110 | cusparseDcsr2dense(cusparseHandle_t         handle,
      | ^~~~~~~~~~~~~~~~~~
```

### PR DESCRIPTION
**Pull request by harrism**
This PR fixes current RAFT C++/CUDA compilation warnings and turns on -Wall to treat warnings as errors.

Fixes #225
Fixes #289

### CODE REVIEW

**Comment by BradReesWork** [comment]
I'm not a fan of relative paths (#include "../test_utils.h"), but PR looks good

**Review by BradReesWork — APPROVED** [review]

**Review by cjnolet — APPROVED** [review]
LGTM

**Comment by cjnolet** [comment]
@gpucibot merge

**Comment by harrism** [comment]
> I'm not a fan of relative paths (#include "../test_utils.h"), but PR looks good

Me neither, but I didn't change that, it was already there. If the build options don't include the base path, and the header is not part of the library public interface, then relative paths are a necessity.

**Pull request merged**
