### PR TITLE
[FEA] Add `bitset_filter` for CAGRA indices removal

### LINKED ISSUE #1600: [FEA] Support vector deletion in CAGRA

### PR DESCRIPTION
**Pull request by lowener**
Closes #1600.
To be merged after #1803 and #1811
This PR adds `bitset_filter` to filter an index with a bitset.

### CODE REVIEW

**Comment by lowener** [comment]
Current benchmark performance on my local machine (with the corresponding `removed_ratio` of 2%, 4%, 8%, ..):
```
AnnCagra/float/uint32_t/21/manual_time       4.09 ms         4.13 ms          171 block_size=256 dataset (GiB)=0.953674 degree=64 graph (GiB)=0.476837 iterations=36 itopk_size=64 k=32 n_cols=128 n_queries=1000 n_rows=2M removed_ratio=0 search_width=2
AnnCagra/float/uint32_t/22/manual_time       4.10 ms         4.14 ms          171 block_size=256 dataset (GiB)=0.953674 degree=64 graph (GiB)=0.476837 iterations=36 itopk_size=64 k=32 n_cols=128 n_queries=1000 n_rows=2M removed_ratio=0.02 search_width=2
AnnCagra/float/uint32_t/23/manual_time       4.10 ms         4.14 ms          171 block_size=256 dataset (GiB)=0.953674 degree=64 graph (GiB)=0.476837 iterations=36 itopk_size=64 k=32 n_cols=128 n_queries=1000 n_rows=2M removed_ratio=0.04 search_width=2
AnnCagra/float/uint32_t/24/manual_time       4.11 ms         4.15 ms          170 block_size=256 dataset (GiB)=0.953674 degree=64 graph (GiB)=0.476837 iterations=36 itopk_size=64 k=32 n_cols=128 n_queries=1000 n_rows=2M removed_ratio=0.08 search_width=2
AnnCagra/float/uint32_t/25/manual_time       4.10 ms         4.14 ms          171 block_size=256 dataset (GiB)=0.953674 degree=64 graph (GiB)=0.476837 iterations=36 itopk_size=64 k=32 n_cols=128 n_queries=1000 n_rows=2M removed_ratio=0.16 search_width=2
AnnCagra/float/uint32_t/26/manual_time       4.09 ms         4.13 ms          171 block_size=256 dataset (GiB)=0.953674 degree=64 graph (GiB)=0.476837 iterations=36 itopk_size=64 k=32 n_cols=128 n_queries=1000 n_rows=2M removed_ratio=0.32 search_width=2
AnnCagra/float/uint32_t/27/manual_time       4.09 ms         4.13 ms          171 block_size=256 dataset (GiB)=0.953674 degree=64 graph (GiB)=0.476837 iterations=36 itopk_size=64 k=32 n_cols=128 n_queries=1000 n_rows=2M removed_ratio=0.64 search_width=2
```

**Comment by lowener** [comment]
Latest benchmark results on my local machine. The difference between `none_filter` and `bitset_filter` is definitely noticeable now.
```
AnnCagra/float/uint32_t/21/manual_time       3.72 ms         3.76 ms          188 block_size=256 dataset (GiB)=0.953674 degree=64 graph (GiB)=0.476837 iterations=36 itopk_size=64 k=32 n_cols=128 n_queries=1000 n_rows=2M removed_ratio=0 search_width=2
AnnCagra/float/uint32_t/22/manual_time       6.15 ms         6.19 ms          114 block_size=256 dataset (GiB)=0.953674 degree=64 graph (GiB)=0.476837 iterations=36 itopk_size=64 k=32 n_cols=128 n_queries=1000 n_rows=2M removed_ratio=0.02 search_width=2
AnnCagra/float/uint32_t/23/manual_time       6.17 ms         6.22 ms          113 block_size=256 dataset (GiB)=0.953674 degree=64 graph (GiB)=0.476837 iterations=36 itopk_size=64 k=32 n_cols=128 n_queries=1000 n_rows=2M removed_ratio=0.04 search_width=2
AnnCagra/float/uint32_t/24/manual_time       6.18 ms         6.22 ms          113 block_size=256 dataset (GiB)=0.953674 degree=64 graph (GiB)=0.476837 iterations=36 itopk_size=64 k=32 n_cols=128 n_queries=1000 n_rows=2M removed_ratio=0.08 search_width=2
AnnCagra/float/uint32_t/25/manual_time       6.19 ms         6.23 ms          113 block_size=256 dataset (GiB)=0.953674 degree=64 graph (GiB)=0.476837 iterations=36 itopk_size=64 k=32 n_cols=128 n_queries=1000 n_rows=2M removed_ratio=0.16 search_width=2
AnnCagra/float/uint32_t/26/manual_time       6.20 ms         6.24 ms          113 block_size=256 dataset (GiB)=0.953674 degree=64 graph (GiB)=0.476837 iterations=36 itopk_size=64 k=32 n_cols=128 n_queries=1000 n_rows=2M removed_ratio=0.32 search_width=2
AnnCagra/float/uint32_t/27/manual_time       6.25 ms         6.28 ms          112 block_size=256 dataset (GiB)=0.953674 degree=64 graph (GiB)=0.476837 iterations=36 itopk_size=64 k=32 n_cols=128 n_queries=1000 n_rows=2M removed_ratio=0.64 search_width=2
```

**Comment by lowener** [comment]
Current result of benchmark of bench-prims on 10M points, batch size 1, 10, 10lk
```
AnnCagra/float/uint32_t/35/manual_time      0.299 ms        0.340 ms         2343 block_size=256 dataset (GiB)=4.76837 degree=64 graph (GiB)=2.38419 iterations=36 itopk_size=64 k=32 n_cols=128 n_queries=1 n_rows=10M removed_ratio=0 search_width=2
AnnCagra/float/uint32_t/36/manual_time      0.332 ms        0.373 ms         2111 block_size=256 dataset (GiB)=4.76837 degree=64 graph (GiB)=2.38419 iterations=36 itopk_size=64 k=32 n_cols=128 n_queries=1 n_rows=10M removed_ratio=0.02 search_width=2
AnnCagra/float/uint32_t/37/manual_time      0.333 ms        0.375 ms         2100 block_size=256 dataset (GiB)=4.76837 degree=64 graph (GiB)=2.38419 iterations=36 itopk_size=64 k=32 n_cols=128 n_queries=1 n_rows=10M removed_ratio=0.04 search_width=2
AnnCagra/float/uint32_t/38/manual_time      0.339 ms        0.381 ms         2062 block_size=256 dataset (GiB)=4.76837 degree=64 graph (GiB)=2.38419 iterations=36 itopk_size=64 k=32 n_cols=128 n_queries=1 n_rows=10M removed_ratio=0.08 search_width=2
AnnCagra/float/uint32_t/39/manual_time      0.351 ms        0.393 ms         1991 block_size=256 dataset (GiB)=4.76837 degree=64 graph (GiB)=2.38419 iterations=36 itopk_size=64 k=32 n_cols=128 n_queries=1 n_rows=10M removed_ratio=0.16 search_width=2
AnnCagra/float/uint32_t/40/manual_time      0.369 ms        0.411 ms         1895 block_size=256 dataset (GiB)=4.76837 degree=64 graph (GiB)=2.38419 iterations=36 itopk_size=64 k=32 n_cols=128 n_queries=1 n_rows=10M removed_ratio=0.32 search_width=2
AnnCagra/float/uint32_t/41/manual_time      0.382 ms        0.424 ms         1831 block_size=256 dataset (GiB)=4.76837 degree=64 graph (GiB)=2.38419 iterations=36 itopk_size=64 k=32 n_cols=128 n_queries=1 n_rows=10M removed_ratio=0.64 search_width=2
AnnCagra/float/uint32_t/42/manual_time      0.308 ms        0.347 ms         2271 block_size=256 dataset (GiB)=4.76837 degree=64 graph (GiB)=2.38419 iterations=36 itopk_size=64 k=32 n_cols=128 n_queries=10 n_rows=10M removed_ratio=0 search_width=2
AnnCagra/float/uint32_t/43/manual_time      0.342 ms        0.381 ms         2047 block_size=256 dataset (GiB)=4.76837 degree=64 graph (GiB)=2.38419 iterations=36 itopk_size=64 k=32 n_cols=128 n_queries=10 n_rows=10M removed_ratio=0.02 search_width=2
AnnCagra/float/uint32_t/44/manual_time      0.344 ms        0.384 ms         2032 block_size=256 dataset (GiB)=4.76837 degree=64 graph (GiB)=2.38419 iterations=36 itopk_size=64 k=32 n_cols=128 n_queries=10 n_rows=10M removed_ratio=0.04 search_width=2
AnnCagra/float/uint32_t/45/manual_time      0.353 ms        0.392 ms         1982 block_size=256 dataset (GiB)=4.76837 degree=64 graph (GiB)=2.38419 iterations=36 itopk_size=64 k=32 n_cols=128 n_queries=10 n_rows=10M removed_ratio=0.08 search_width=2
AnnCagra/float/uint32_t/46/manual_time      0.360 ms        0.399 ms         1945 block_size=256 dataset (GiB)=4.76837 degree=64 graph (GiB)=2.38419 iterations=36 itopk_size=64 k=32 n_cols=128 n_queries=10 n_rows=10M removed_ratio=0.16 search_width=2
AnnCagra/float/uint32_t/47/manual_time      0.382 ms        0.421 ms         1834 block_size=256 dataset (GiB)=4.76837 degree=64 graph (GiB)=2.38419 iterations=36 itopk_size=64 k=32 n_cols=128 n_queries=10 n_rows=10M removed_ratio=0.32 search_width=2
AnnCagra/float/uint32_t/48/manual_time      0.393 ms        0.433 ms         1779 block_size=256 dataset (GiB)=4.76837 degree=64 graph (GiB)=2.38419 iterations=36 itopk_size=64 k=32 n_cols=128 n_queries=10 n_rows=10M removed_ratio=0.64 search_width=2
AnnCagra/float/uint32_t/49/manual_time       37.4 ms         37.4 ms           19 block_size=256 dataset (GiB)=4.76837 degree=64 graph (GiB)=2.38419 iterations=36 itopk_size=64 k=32 n_cols=128 n_queries=10k n_rows=10M removed_ratio=0 search_width=2
AnnCagra/float/uint32_t/50/manual_time       62.0 ms         62.0 ms           11 block_size=256 dataset (GiB)=4.76837 degree=64 graph (GiB)=2.38419 iterations=36 itopk_size=64 k=32 n_cols=128 n_queries=10k n_rows=10M removed_ratio=0.02 search_width=2
AnnCagra/float/uint32_t/51/manual_time       62.1 ms         62.1 ms           11 block_size=256 dataset (GiB)=4.76837 degree=64 graph (GiB)=2.38419 iterations=36 itopk_size=64 k=32 n_cols=128 n_queries=10k n_rows=10M removed_ratio=0.04 search_width=2
AnnCagra/float/uint32_t/52/manual_time       62.3 ms         62.3 ms           11 block_size=256 dataset (GiB)=4.76837 degree=64 graph (GiB)=2.38419 iterations=36 itopk_size=64 k=32 n_cols=128 n_queries=10k n_rows=10M removed_ratio=0.08 search_width=2
AnnCagra/float/uint32_t/53/manual_time       62.8 ms         62.4 ms           11 block_size=256 dataset (GiB)=4.76837 degree=64 graph (GiB)=2.38419 iterations=36 itopk_size=64 k=32 n_cols=128 n_queries=10k n_rows=10M removed_ratio=0.16 search_width=2
AnnCagra/float/uint32_t/54/manual_time       62.4 ms         62.4 ms           11 block_size=256 dataset (GiB)=4.76837 degree=64 graph (GiB)=2.38419 iterations=36 itopk_size=64 k=32 n_cols=128 n_queries=10k n_rows=10M removed_ratio=0.32 search_width=2
AnnCagra/float/uint32_t/55/manual_time       62.9 ms         62.9 ms           11 block_size=256 dataset (GiB)=4.76837 degree=64 graph (GiB)=2.38419 iterations=36 itopk_size=64 k=32 n_cols=128 n_queries=10k n_rows=10M removed_ratio=0.64 search_width=2
```

**Comment by lowener** [comment]
```
AnnCagra/float/uint32_t/35/manual_time       2.52 ms         2.56 ms          277 block_size=256 dataset (GiB)=4.76837 degree=64 graph (GiB)=2.38419 iterations=161 itopk_size=300 k=255 n_cols=128 n_queries=1 n_rows=10M removed_ratio=0 search_width=2
AnnCagra/float/uint32_t/36/manual_time       2.33 ms         2.36 ms          301 block_size=256 dataset (GiB)=4.76837 degree=64 graph (GiB)=2.38419 iterations=161 itopk_size=300 k=255 n_cols=128 n_queries=1 n_rows=10M removed_ratio=0.02 search_width=2
AnnCagra/float/uint32_t/37/manual_time       2.41 ms         2.45 ms          290 block_size=256 dataset (GiB)=4.76837 degree=64 graph (GiB)=2.38419 iterations=161 itopk_size=300 k=255 n_cols=128 n_queries=1 n_rows=10M removed_ratio=0.04 search_width=2
AnnCagra/float/uint32_t/38/manual_time       2.58 ms         2.62 ms          271 block_size=256 dataset (GiB)=4.76837 degree=64 graph (GiB)=2.38419 iterations=161 itopk_size=300 k=255 n_cols=128 n_queries=1 n_rows=10M removed_ratio=0.08 search_width=2
AnnCagra/float/uint32_t/39/manual_time       2.83 ms         2.86 ms          247 block_size=256 dataset (GiB)=4.76837 degree=64 graph (GiB)=2.38419 iterations=161 itopk_size=300 k=255 n_cols=128 n_queries=1 n_rows=10M removed_ratio=0.16 search_width=2
AnnCagra/float/uint32_t/40/manual_time       3.37 ms         3.41 ms          207 block_size=256 dataset (GiB)=4.76837 degree=64 graph (GiB)=2.38419 iterations=161 itopk_size=300 k=255 n_cols=128 n_queries=1 n_rows=10M removed_ratio=0.32 search_width=2
AnnCagra/float/uint32_t/41/manual_time       3.86 ms         3.90 ms          181 block_size=256 dataset (GiB)=4.76837 degree=64 graph (GiB)=2.38419 iterations=161 itopk_size=300 k=255 n_cols=128 n_queries=1 n_rows=10M removed_ratio=0.64 search_width=2
AnnCagra/float/uint32_t/42/manual_time       2.59 ms         2.63 ms          270 block_size=256 dataset (GiB)=4.76837 degree=64 graph (GiB)=2.38419 iterations=161 itopk_size=300 k=255 n_cols=128 n_queries=10 n_rows=10M removed_ratio=0 search_width=2
AnnCagra/float/uint32_t/43/manual_time       2.52 ms         2.56 ms          278 block_size=256 dataset (GiB)=4.76837 degree=64 graph (GiB)=2.38419 iterations=161 itopk_size=300 k=255 n_cols=128 n_queries=10 n_rows=10M removed_ratio=0.02 search_width=2
AnnCagra/float/uint32_t/44/manual_time       2.59 ms         2.63 ms          270 block_size=256 dataset (GiB)=4.76837 degree=64 graph (GiB)=2.38419 iterations=161 itopk_size=300 k=255 n_cols=128 n_queries=10 n_rows=10M removed_ratio=0.04 search_width=2
AnnCagra/float/uint32_t/45/manual_time       2.73 ms         2.77 ms          256 block_size=256 dataset (GiB)=4.76837 degree=64 graph (GiB)=2.38419 iterations=161 itopk_size=300 k=255 n_cols=128 n_queries=10 n_rows=10M removed_ratio=0.08 search_width=2
AnnCagra/float/uint32_t/46/manual_time       3.01 ms         3.05 ms          232 block_size=256 dataset (GiB)=4.76837 degree=64 graph (GiB)=2.38419 iterations=161 itopk_size=300 k=255 n_cols=128 n_queries=10 n_rows=10M removed_ratio=0.16 search_width=2
AnnCagra/float/uint32_t/47/manual_time       3.64 ms         3.67 ms          192 block_size=256 dataset (GiB)=4.76837 degree=64 graph (GiB)=2.38419 iterations=161 itopk_size=300 k=255 n_cols=128 n_queries=10 n_rows=10M removed_ratio=0.32 search_width=2
AnnCagra/float/uint32_t/48/manual_time       4.02 ms         4.06 ms          174 block_size=256 dataset (GiB)=4.76837 degree=64 graph (GiB)=2.38419 iterations=161 itopk_size=300 k=255 n_cols=128 n_queries=10 n_rows=10M removed_ratio=0.64 search_width=2
AnnCagra/float/uint32_t/49/manual_time        485 ms          485 ms            2 block_size=256 dataset (GiB)=4.76837 degree=64 graph (GiB)=2.38419 iterations=161 itopk_size=300 k=255 n_cols=128 n_queries=10k n_rows=10M removed_ratio=0 search_width=2
AnnCagra/float/uint32_t/50/manual_time        632 ms          631 ms            1 block_size=256 dataset (GiB)=4.76837 degree=64 graph (GiB)=2.38419 iterations=161 itopk_size=300 k=255 n_cols=128 n_queries=10k n_rows=10M removed_ratio=0.02 search_width=2
AnnCagra/float/uint32_t/51/manual_time        629 ms          629 ms            1 block_size=256 dataset (GiB)=4.76837 degree=64 graph (GiB)=2.38419 iterations=161 itopk_size=300 k=255 n_cols=128 n_queries=10k n_rows=10M removed_ratio=0.04 search_width=2
AnnCagra/float/uint32_t/52/manual_time        631 ms          624 ms            1 block_size=256 dataset (GiB)=4.76837 degree=64 graph (GiB)=2.38419 iterations=161 itopk_size=300 k=255 n_cols=128 n_queries=10k n_rows=10M removed_ratio=0.08 search_width=2
AnnCagra/float/uint32_t/53/manual_time        617 ms          617 ms            1 block_size=256 dataset (GiB)=4.76837 degree=64 graph (GiB)=2.38419 iterations=161 itopk_size=300 k=255 n_cols=128 n_queries=10k n_rows=10M removed_ratio=0.16 search_width=2
AnnCagra/float/uint32_t/54/manual_time        608 ms          607 ms            1 block_size=256 dataset (GiB)=4.76837 degree=64 graph (GiB)=2.38419 iterations=161 itopk_size=300 k=255 n_cols=128 n_queries=10k n_rows=10M removed_ratio=0.32 search_width=2
AnnCagra/float/uint32_t/55/manual_time        605 ms          604 ms            1 block_size=256 dataset (GiB)=4.76837 degree=64 graph (GiB)=2.38419 iterations=161 itopk_size=300 k=255 n_cols=128 n_queries=10k n_rows=10M removed_ratio=0.64 search_width=2
```

**Review by cjnolet — APPROVED** [review]
LGTM!

**Comment by cjnolet** [comment]
@lowener, I've approved this PR and I think the implementation looks good. The only thing lacking now is documentation. We should add a separate usage example to `raft::cagra::search_with_filtering` for specifying the bitset sample filter.

**Pull request merged**
