### PR TITLE
Fix C++ doxygen documentation

### PR DESCRIPTION
**Pull request by achirkin**
Make the doxygen docs buildable again. The changes:

1. A minimal set of changes required for `docs_raft` target to complete successfully
2. A `build.sh` section for building the docs target (as in cuml)
3. CI target to make sure new documentation errors do not slip in.

### CODE REVIEW

**Comment by achirkin** [comment]
rerun tests

**Review by cjnolet — APPROVED** [review]
Changes look great. Thanks for fixing this!

**Review by ajschmidt8 — APPROVED** [review]
Approving `ops-codeowner` file changes

**Comment by cjnolet** [comment]
@gpucibot merge

**Pull request merged**
