### PR TITLE
Add support for 1024+ dim vectors in CAGRA search

### PR DESCRIPTION
**Pull request by enp1s0**
This PR updates the CAGRA search implementation to support 1024+ dim vectors.
For 1024+ dim vectors, the distance between a vector and the query vector is calculated by splitting the vector into multiple 1024 dim vectors and accumulating the distances of each sub-vector.

Rel: #1948

### CODE REVIEW

**Comment by enp1s0** [comment]
- [ ] single-CAT
- [ ] multi-CAT
- [ ] multi-kernel

**Comment by enp1s0** [comment]
No significant performance drop is observed
s1024+

**Review by cjnolet — APPROVED** [review]
LGTM! This is an important feature and we have folks from Lucene and Lantern waiting on this. These changes look good, but we can follow up if anyone else sees any issues.

**Review by tfeher — COMMENTED** [review]
Thanks @enp1s0 for the PR, it looks good to me.

**Pull request merged**
