### PR TITLE
Unpin `dask` and `distributed` for development and fix `merge_labels` test

### PR DESCRIPTION
**Pull request by galipremsagar**
This PR unpins `dask` and `distributed` to `>=2023.5.1` for `23.08` development.

xref: https://github.com/rapidsai/cudf/pull/13508

The offending test was using an rmm::device_scalar for some memory that should have been a vector. Not sure how this didn't fail in the past but these changes fix it.

### CODE REVIEW

**Review by raydouglass — APPROVED** [review]

**Review by cjnolet — APPROVED** [review]

**Comment by galipremsagar** [comment]
Merged changes from https://github.com/rapidsai/raft/pull/1577, to pass the CI in this PR.

**Review by cjnolet — APPROVED** [review]
LGTM

**Comment by cjnolet** [comment]
Wow, completely confused why this pytest is suddenly failing only for a single configuration.

**Comment by galipremsagar** [comment]
> Wow, completely confused why this pytest is suddenly failing only for a single configuration.

Looks like third time's a charm, :phew:

**Pull request merged**
