### PR TITLE
Branch 23.02 merge 22.12

### PR DESCRIPTION
**Pull request by benfred**
PR to unblock forward merge https://github.com/rapidsai/raft/pull/1018 -

### CODE REVIEW

**Comment by vyasr** [comment]
This PR is massive. Have the 22.12->23.02 merges been off for a long time, or were they blocked by the pre-commit linters run causing merge conflicts (I see that's the first unmerged commit)?

**Comment by benfred** [comment]
> This PR is massive. Have the 22.12->23.02 merges been off for a long time, or were they blocked by the pre-commit linters run causing merge conflicts (I see that's the first unmerged commit)?

Yeah - there was a merge conflict because of the pre-commit linters. That commit modified the `cpp/CMakeLists.txt` file (with auto formatting cmake), which conflicted with the change to bump the version number for 23.02 =(. 

All I did in this PR is follow the steps here https://docs.rapids.ai/maintainers/gpuci/#forward-mergers , and resolve the merge conflict

**Comment by vyasr** [comment]
Yup I'm sure you did the right thing with the forward merger, I was just a little concerned since the size of the PR makes it almost impossible to verify the correctness of the merge (at least for me, but I'm also no raft expert).

**Review by msadang — APPROVED** [review]
LGTM

**Review by cjnolet — APPROVED** [review]

**Pull request merged**
