### PR TITLE
[REVIEW] Adding canberra and chebyshev to distance types

### PR DESCRIPTION
**Pull request by cjnolet**

### CODE REVIEW

**Comment by GPUtester** [comment]
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

**Review by dantegd — APPROVED** [review]
change lgtm pending changelog entry

**Comment by dantegd** [comment]
@cjnolet would it be ok to re-target this PR to branch-0.18?

**Comment by JohnZed** [comment]
will hold to 0.18

**Pull request merged**
