### PR TITLE
Use rapids-cmake for cuco

### PR DESCRIPTION
**Pull request by vyasr**
This ensures that a consistent cuco version is used across all of RAPIDS. See https://github.com/rapidsai/rapids-cmake/pull/201 and https://github.com/rapidsai/cudf/pull/11139

### CODE REVIEW

**Comment by vyasr** [comment]
rerun tests

**Comment by vyasr** [comment]
Interesting, now I am also seeing failures in `SelectionTest/ReferencedRandomFloatInt` and `SelectionTest/ReferencedRandomDoubleSizeT`. These seem like very different errors, than the distance error, but perhaps they share some underlying cause?

**Comment by cjnolet** [comment]
rerun tests

**Comment by vyasr** [comment]
@gpucibot merge

**Pull request merged**
