### PR TITLE
[REVIEW] Modify default value for rowMajorIndex and rowMajorQuery in bf-knn

### PR DESCRIPTION
**Pull request by viclafargue**
This PR modifies the default value for `rowMajorIndex` and `rowMajorQuery` parameters in `brute_force_knn`.

### CODE REVIEW

**Comment by cjnolet** [comment]
@hlinsen, this PR modifies the default values for the `rowMajorIndex` and `rowMajorQuery` arguments. There was also a recent PR that removed the `expanded` argument from `brute_force_knn`. I wanted to make sure you are aware of this so cugraph can be updated and we can avoid any unexpected problems during the coming release. 

also cc @JohnZed

**Comment by hlinsen** [comment]
> @hlinsen, this PR modifies the default values for the `rowMajorIndex` and `rowMajorQuery` arguments. There was also a recent PR that removed the `expanded` argument from `brute_force_knn`. I wanted to make sure you are aware of this so cugraph can be updated and we can avoid any unexpected problems during the coming release.
> 
> also cc @JohnZed

Sounds good. This shouldn't cause issues, if there are I have a PR coming soon with TSP fixes so I'll make the necessary changes there.

**Comment by cjnolet** [comment]
@viclafargue, I've opened https://github.com/rapidsai/raft/pull/178, which should fix the CUDA11 failing SLHC test. I'm still working to find the cause / fix for the CUDA10.1/2 hang issue.

**Review by cjnolet — APPROVED** [review]
LGTM

**Comment by cjnolet** [comment]
@gpucibot merge

**Comment by cjnolet** [comment]
rerun tests

**Comment by cjnolet** [comment]
@viclafargue, the PR to fix the linkage test went through last night. Just merged branch-0.19 into your branch in hopes we might finally be able to get this PR merged.

**Comment by cjnolet** [comment]
@gpucibot merge

**Pull request merged**
