### PR TITLE
Make ucx linkage explicit and add a new CMake target for it

### LINKED ISSUE #1031: [FEA] Remove `dlopen` of ucx from std_comms
We initially used dlopen in the std_comms because ucx wasn't yet fully integrated into the rapids software stack and so it was harder to link directly against ucx. Now that we can do so, it's making the build process unnecessarily confusing and complicated, since we directly like against ucx in the python package but then still dlopen in the c++ layer, expecting ucx to be magically available on the system ld path. 

This should be a fairly trivial change, but will also require downstream projects to link against ucx directly as well in their c++ code. Thankfully, as @vyasr pointed out, the new version of ucx supports find_package.

### PR DESCRIPTION
**Pull request by vyasr**
This PR removes the dlopen logic for libucp in ucp_helper.hpp in favor of calling the relevant APIs directly. It also adds a new CMake component `raft::distributed` that can be used by dependent libraries to indicate the dependency on parts of raft that require UCX.

While it does not change any public APIs, I have marked this PR as breaking since it does mean that any C++ code linking to UCX must now ensure that UCX is available at link time. It is no longer sufficient to make the library available at runtime.

Resolves #1031.

### CODE REVIEW

**Comment by vyasr** [comment]
rerun tests

**Comment by cjnolet** [comment]
Thanks for fixing this, @vyasr.  Now we just need to add ucx as an explicit link dependency of cuml and cugraph

**Comment by vyasr** [comment]
> Thanks for fixing this, @vyasr. Now we just need to add ucx as an explicit link dependency of cuml and cugraph

Done.

**Comment by cjnolet** [comment]
@robertmaynard this adds a new optional component for `distributed` (which currently adds ucx but will add NCCL in the future). Any chance we can get your blessing on these changes?

**Review by cjnolet — APPROVED** [review]
LGTM, thanks @vyasr!

**Comment by cjnolet** [comment]
@gpucibot merge

**Comment by cjnolet** [comment]
@gpucibot merge

**Pull request merged**
